import type { ServiceHubContent } from "./service-hub-content";

type Context = { countryName: string; locale: string; serviceNames: string[] };
type Locale = "es" | "ro" | "de";
type LocalizedContent = Omit<ServiceHubContent, "resolvedLocale"> & { resolvedLocale: Locale };

const specialist = (l: Locale, c: Context): LocalizedContent => {
  const es = l === "es";
  const ro = l === "ro";
  const t = <T>(a: T, b: T, d: T) => (es ? a : ro ? b : d);
  return {
    resolvedLocale: l,
    overview: {
      eyebrow: t("Descripción general", "Prezentare generală", "Überblick"),
      title: t("Atención especializada vinculada a un servicio activo", "Îngrijire de specialitate asociată unui serviciu activ", "Fachärztliche Versorgung passend zu einem aktiven Angebot"),
      body: t(
        `Global Health muestra las consultas en línea con especialistas disponibles actualmente en ${c.countryName}. La disponibilidad depende del servicio, del profesional y de la agenda. Algunos problemas requieren una exploración presencial u otro entorno asistencial.`,
        `Global Health listează consultațiile online de specialitate disponibile în prezent în ${c.countryName}. Disponibilitatea depinde de serviciu, de cadrul medical și de program. Unele probleme necesită o examinare în persoană sau un alt cadru de îngrijire.`,
        `Global Health führt die derzeit in ${c.countryName} verfügbaren fachärztlichen Online-Sprechstunden auf. Die Verfügbarkeit hängt von Leistung, Fachkraft und Terminplan ab. Manche Anliegen erfordern eine Untersuchung vor Ort oder eine andere Versorgungsform.`,
      ),
    },
    whoFor: {
      eyebrow: t("A quién puede resultar adecuado", "Cui i se poate potrivi", "Für wen es geeignet sein kann"),
      title: t("Cuándo puede plantearse reservar", "Când puteți lua în considerare o programare", "Wann eine Buchung infrage kommen kann"),
      intro: t("Puede ser útil si desea comentar un problema con un profesional de un área concreta.", "Poate fi utilă dacă doriți să discutați o problemă cu un cadru medical dintr-un anumit domeniu.", "Sie kann sinnvoll sein, wenn Sie ein Anliegen mit einer Fachkraft eines bestimmten Gebiets besprechen möchten."),
      items: t(
        ["Le han recomendado una valoración por un especialista", "Desea comentar un problema existente o un seguimiento previsto", "Busca otra opinión clínica cuando resulte apropiado", "Desea saber si una consulta especializada en línea es un siguiente paso adecuado"],
        ["Vi s-a recomandat o evaluare de specialitate", "Doriți să discutați o problemă existentă sau o monitorizare planificată", "Doriți o altă opinie clinică, atunci când este adecvat", "Doriți să aflați dacă o consultație online de specialitate este un pas potrivit"],
        ["Ihnen wurde eine fachärztliche Abklärung empfohlen", "Sie möchten ein bestehendes Anliegen oder eine geplante Nachsorge besprechen", "Sie wünschen, soweit angemessen, eine weitere ärztliche Einschätzung", "Sie möchten klären, ob eine fachärztliche Online-Sprechstunde ein geeigneter nächster Schritt ist"],
      ),
    },
    commonReasons: c.serviceNames.length ? {
      eyebrow: t("Áreas disponibles", "Domenii disponibile", "Verfügbare Fachgebiete"),
      title: t("Motivos para elegir una consulta con un especialista", "Motive pentru alegerea unei consultații de specialitate", "Gründe für eine fachärztliche Sprechstunde"),
      intro: t("Los servicios especializados activos para este país son:", "Serviciile de specialitate active pentru această țară sunt:", "Für dieses Land sind derzeit folgende Fachleistungen aktiv:"),
      items: c.serviceNames,
      note: t("Consulte el alcance del servicio antes de reservar. Un profesional decidirá si una cita en línea es adecuada.", "Consultați domeniul serviciului înainte de programare. Un cadru medical decide dacă o consultație online este potrivită.", "Prüfen Sie vor der Buchung den Leistungsumfang. Eine Fachkraft entscheidet, ob ein Online-Termin geeignet ist."),
    } : undefined,
    process: {
      eyebrow: t("Cómo funciona", "Cum funcționează", "So funktioniert es"),
      title: t("Desde la selección hasta el seguimiento", "De la alegere la monitorizare", "Von der Auswahl bis zur Nachsorge"),
      steps: t(
        [["Seleccione un servicio", "Revise los servicios activos y sus datos publicados."], ["Elija un médico disponible", "Solo se ofrecen profesionales asignados al servicio elegido."], ["Elija una cita", "Seleccione un horario disponible para ese médico y servicio."], ["Complete la reserva", "Introduzca los datos requeridos y pague cuando corresponda."], ["Asista en línea", "Use la información incluida en la confirmación."], ["Revise los siguientes pasos", "El seguimiento, los documentos, las pruebas o derivaciones dependen del criterio clínico y del servicio."]],
        [["Selectați un serviciu", "Consultați serviciile active și detaliile publicate."], ["Alegeți un medic eligibil", "Sunt oferiți numai specialiștii alocați serviciului ales."], ["Alegeți o programare", "Selectați un interval disponibil pentru medicul și serviciul respectiv."], ["Finalizați programarea", "Introduceți datele solicitate și plătiți, dacă este cazul."], ["Participați online", "Folosiți informațiile din confirmare."], ["Consultați pașii următori", "Monitorizarea, documentele, analizele sau trimiterile depind de raționamentul clinic și de serviciu."]],
        [["Leistung auswählen", "Prüfen Sie aktive Leistungen und veröffentlichte Angaben."], ["Berechtigte Ärztin oder berechtigten Arzt wählen", "Buchbar sind nur der gewählten Leistung zugeordnete Fachkräfte."], ["Termin wählen", "Wählen Sie einen verfügbaren Termin für diese Fachkraft und Leistung."], ["Buchung abschließen", "Geben Sie die erforderlichen Daten ein und bezahlen Sie, falls zutreffend."], ["Online teilnehmen", "Nutzen Sie die Angaben in Ihrer Buchungsbestätigung."], ["Nächste Schritte prüfen", "Nachsorge, Dokumente, Tests oder Überweisungen hängen von der ärztlichen Beurteilung und Leistung ab."]],
      ).map(([title, body]) => ({ title, body })),
    },
    whyChoose: {
      eyebrow: t("Por qué Global Health", "De ce Global Health", "Warum Global Health"),
      title: t("Información clara antes de reservar", "Informații clare înainte de programare", "Klare Informationen vor der Buchung"),
      items: t(
        ["Disponibilidad de profesionales y servicios por país", "Perfiles transparentes e idiomas indicados", "Datos de colegiación cuando hay información verificada", "Precios y duración cuando están configurados", "Reserva segura y confirmación", "Cada reserva incluye un servicio especializado asignado válido"],
        ["Disponibilitatea cadrelor medicale și serviciilor pentru fiecare țară", "Profiluri transparente și limbile indicate", "Detalii de înregistrare profesională când există date verificate", "Prețuri și durată când sunt configurate", "Programare securizată și confirmare", "Fiecare programare include un serviciu de specialitate alocat valabil"],
        ["Länderbezogene Verfügbarkeit von Fachkräften und Leistungen", "Transparente Profile und angegebene Sprachen", "Registrierungsangaben bei verifizierten Daten", "Preise und Dauer, sofern hinterlegt", "Sichere Online-Buchung und Bestätigung", "Jede Arztbuchung enthält eine gültig zugeordnete Fachleistung"],
      ),
    },
    importantInformation: {
      eyebrow: t("Información importante", "Informații importante", "Wichtige Hinweise"),
      title: t("La atención especializada en línea tiene limitaciones", "Îngrijirea online de specialitate are limite", "Fachärztliche Online-Versorgung hat Grenzen"),
      paragraphs: t(
        ["Las consultas en línea no son adecuadas para emergencias. Si necesita ayuda urgente, contacte con el servicio de emergencias local.", "Algunos síntomas requieren exploración física, valoración urgente o pruebas presenciales. El profesional puede recomendar otro entorno asistencial.", "No se garantizan recetas, pruebas, derivaciones, certificados, tratamientos ni otros documentos. Dependen del criterio clínico y las normas locales.", `Los servicios, profesionales, precios y horarios varían en ${c.countryName} y pueden cambiar al actualizarse el catálogo.`],
        ["Consultațiile online nu sunt potrivite pentru urgențe. Pentru ajutor urgent, contactați serviciul local de urgență.", "Unele simptome necesită examinare fizică, evaluare urgentă sau analize în persoană. Cadrul medical poate recomanda alt cadru de îngrijire.", "Rețetele, analizele, trimiterile, certificatele, tratamentele și alte documente nu sunt garantate. Acestea depind de raționamentul clinic și normele locale.", `Serviciile, cadrele medicale, prețurile și programările variază în ${c.countryName} și se pot modifica odată cu actualizarea catalogului.`],
        ["Online-Sprechstunden eignen sich nicht für Notfälle. Wenden Sie sich bei dringendem Hilfebedarf an den örtlichen Notdienst.", "Manche Beschwerden erfordern eine körperliche Untersuchung, dringende Abklärung oder Tests vor Ort. Die Fachkraft kann eine andere Versorgung empfehlen.", "Rezepte, Tests, Überweisungen, Bescheinigungen, Behandlungen und andere Unterlagen sind nicht garantiert. Sie hängen von der ärztlichen Beurteilung und örtlichen Regeln ab.", `Leistungen, Fachkräfte, Preise und Termine unterscheiden sich in ${c.countryName} und können sich mit dem aktiven Katalog ändern.`],
      ),
    },
    faq: t(
      [["¿Cómo funciona una consulta en línea?", "Elija un servicio activo, un profesional asignado y una cita disponible, y complete la reserva."], ["¿Necesito una derivación?", "Los requisitos dependen del servicio y la situación clínica. Consulte los datos y facilite la información solicitada."], ["¿Qué especialidades están disponibles?", "Las tarjetas muestran los servicios activos para el país seleccionado. La disponibilidad puede cambiar."], ["¿Cómo se seleccionan los médicos?", "Aparecen médicos activos en el país con asignación activa a un servicio mostrado. La etiqueta de especialidad no determina por sí sola la disponibilidad."], ["¿Cuánto cuesta y dura?", "Cuando están configurados, las tarjetas muestran precio inicial y duración. Compruebe los datos antes de pagar."], ["¿Es adecuada para cualquier problema?", "No. Puede recomendarse una valoración urgente o presencial si el problema no puede abordarse en línea con seguridad."]],
      [["Cum funcționează o consultație online?", "Alegeți un serviciu activ, un cadru medical alocat și o programare disponibilă, apoi finalizați rezervarea."], ["Am nevoie de trimitere?", "Cerințele depind de serviciu și situația clinică. Verificați detaliile și furnizați informațiile solicitate."], ["Ce specialități sunt disponibile?", "Cardurile arată serviciile active pentru țara selectată. Disponibilitatea se poate modifica."], ["Cum sunt selectați medicii afișați?", "Apar medicii activi în țară, alocați activ cel puțin unui serviciu afișat. Eticheta specialității nu stabilește singură eligibilitatea."], ["Cât costă și durează?", "Când sunt configurate, cardurile arată prețul de pornire și durata. Verificați detaliile înainte de plată."], ["Este potrivită pentru orice problemă?", "Nu. Poate fi recomandată o evaluare urgentă sau în persoană dacă problema nu poate fi abordată online în siguranță."]],
      [["Wie funktioniert eine Online-Sprechstunde?", "Wählen Sie eine aktive Fachleistung, eine zugeordnete Fachkraft und einen verfügbaren Termin und schließen Sie die Buchung ab."], ["Brauche ich eine Überweisung?", "Die Anforderungen hängen von Leistung und klinischer Situation ab. Prüfen Sie die Leistungsangaben und reichen Sie angeforderte Informationen ein."], ["Welche Fachgebiete sind verfügbar?", "Die Karten zeigen die derzeit aktiven Fachleistungen für das gewählte Land. Die Verfügbarkeit kann sich ändern."], ["Wie werden die angezeigten Ärzte ausgewählt?", "Angezeigt werden aktive Ärzte des Landes mit aktiver Zuordnung zu mindestens einer gezeigten Fachleistung. Fachgebietsbezeichnungen allein bestimmen nicht die Buchbarkeit."], ["Was kostet eine Sprechstunde und wie lange dauert sie?", "Sofern hinterlegt, zeigt jede Karte Startpreis und Dauer. Prüfen Sie Leistung, Arzt und Termin vor der Zahlung."], ["Ist eine Online-Sprechstunde für jedes Anliegen geeignet?", "Nein. Wenn das Anliegen online nicht sicher geklärt werden kann, kann eine dringende oder persönliche Untersuchung empfohlen werden."]],
    ).map(([question, answer]) => ({ question, answer })),
    emptyState: { title: t("No hay especialistas disponibles para reservar", "Nu există specialiști disponibili pentru programare", "Keine Fachkräfte zur Buchung verfügbar"), body: t("Actualmente no hay asignaciones activas entre médicos y servicios especializados para este país. Consulte el catálogo o vuelva más tarde.", "În prezent nu există alocări active între medici și servicii de specialitate pentru această țară. Consultați catalogul sau reveniți mai târziu.", "Derzeit gibt es für dieses Land keine aktiven Zuordnungen zwischen Ärzten und Fachleistungen. Prüfen Sie den Katalog oder versuchen Sie es später erneut.") },
  };
};

const tests = (l: Locale, c: Context): LocalizedContent => {
  const es = l === "es"; const ro = l === "ro"; const t = <T>(a:T,b:T,d:T)=>(es?a:ro?b:d);
  return {
    resolvedLocale:l,
    overview:{eyebrow:t("Descripción general","Prezentare generală","Überblick"),title:t("Pruebas de salud con información específica","Teste de sănătate cu informații specifice","Gesundheitstests mit produktspezifischen Angaben"),body:t(`Esta página muestra las pruebas disponibles actualmente en ${c.countryName}. Cada prueba tiene su propio precio, existencias, información de muestra y plazo estimado cuando están configurados.`,`Această pagină listează testele disponibile în prezent în ${c.countryName}. Fiecare test are propriul preț, stoc, informații despre probă și termen estimat, când sunt configurate.`,`Diese Seite zeigt die derzeit in ${c.countryName} verfügbaren Gesundheitstests. Jeder Test hat eigene Angaben zu Preis, Bestand, Probe und erwarteter Ergebnisdauer, sofern hinterlegt.`)},
    whoFor:{eyebrow:t("A quién puede resultar adecuado","Cui i se poate potrivi","Für wen es geeignet sein kann"),title:t("Cuándo puede ser útil una prueba","Când poate fi util un test","Wann ein Gesundheitstest sinnvoll sein kann"),intro:t("Una prueba puede aportar información sobre una cuestión de salud descrita en su página.","Un test poate oferi informații despre o întrebare de sănătate descrisă pe pagina sa.","Ein Test kann Informationen zu einer auf der Produktseite beschriebenen Gesundheitsfrage liefern."),items:t(["Desea revisar los marcadores incluidos","Le han recomendado una prueba concreta","Puede seguir las instrucciones de la muestra","Entiende que un resultado no sustituye una valoración urgente o integral"],["Doriți să consultați markerii incluși","Vi s-a recomandat un anumit test","Puteți urma instrucțiunile privind proba","Înțelegeți că rezultatul nu înlocuiește evaluarea urgentă sau completă"],["Sie möchten die erfassten Marker prüfen","Ihnen wurde ein bestimmter Test empfohlen","Sie können die Probenanleitung befolgen","Sie verstehen, dass ein Ergebnis keine dringende oder umfassende Untersuchung ersetzt"])},
    process:{eyebrow:t("Pedido","Comandă","Bestellung"),title:t("Cómo funciona el pedido","Cum funcționează comanda","So funktioniert die Bestellung"),steps:t([["Revise una prueba","Compruebe alcance, muestra, precio, existencias y plazo publicados."],["Añádala al carrito","Hágalo solo si está disponible y se ajusta a sus necesidades."],["Complete el pago","Confirme pedido, datos del paciente, precio y cargos."],["Siga las instrucciones","Use las instrucciones de recogida, devolución o cita de la prueba."]],[["Consultați testul","Verificați domeniul, proba, prețul, stocul și termenul publicat."],["Adăugați-l în coș","Faceți acest lucru numai dacă este disponibil și corespunde nevoilor."],["Finalizați comanda","Confirmați comanda, datele pacientului, prețul și taxele."],["Urmați instrucțiunile","Folosiți instrucțiunile de recoltare, returnare sau programare."]],[["Test prüfen","Prüfen Sie Umfang, Probe, Preis, Bestand und veröffentlichte Dauer."],["In den Warenkorb legen","Nur wenn der Test verfügbar ist und zu Ihrem Bedarf passt."],["Bestellung abschließen","Prüfen Sie Bestellung, Patientendaten, Preis und Gebühren."],["Anweisungen befolgen","Nutzen Sie die Vorgaben zu Entnahme, Rücksendung oder Termin."]]).map(([title,body])=>({title,body}))},
    secondaryProcess:{eyebrow:t("Recogida de muestras","Recoltarea probei","Probenentnahme"),title:t("El proceso depende de la prueba","Procesul depinde de test","Der Ablauf hängt vom Test ab"),steps:t([["Compruebe el tipo de muestra","El catálogo lo muestra cuando está disponible."],["Lea las instrucciones","La preparación, recogida y el transporte pueden variar."],["Use la modalidad indicada","Confirme antes de pedir las condiciones de entrega, recogida, clínica o devolución."]],[["Verificați tipul probei","Catalogul îl afișează când este disponibil."],["Citiți instrucțiunile","Pregătirea, recoltarea și transportul pot varia."],["Folosiți modalitatea indicată","Confirmați înainte de comandă livrarea, recoltarea, clinica sau returnarea."]],[["Probenart prüfen","Der Katalog zeigt sie, sofern verfügbar."],["Produktanleitung lesen","Vorbereitung, Entnahme und Transport können abweichen."],["Angegebenen Weg nutzen","Klären Sie Lieferung, Entnahme, Klinikbesuch oder Rücksendung vor der Bestellung."]]).map(([title,body])=>({title,body}))},
    results:{eyebrow:t("Resultados y siguientes pasos","Rezultate și pașii următori","Ergebnisse und nächste Schritte"),title:t("Consulte el plazo y seguimiento de su prueba","Consultați termenul și monitorizarea testului","Zeitangaben und Nachsorge des Tests prüfen"),paragraphs:t(["El plazo mostrado es una estimación del producto, no una garantía para cada pedido.","La forma de entrega y cualquier revisión clínica deben indicarse en cada prueba; no todas incluyen consulta.","Un resultado puede requerir interpretación junto con síntomas, antecedentes, exploración u otras pruebas. Solicite asesoramiento si tiene dudas."],["Termenul afișat este o estimare pentru produs, nu o garanție pentru fiecare comandă.","Furnizarea rezultatelor și orice evaluare clinică trebuie precizate pentru fiecare test; nu toate includ consultație.","Rezultatul poate necesita interpretare alături de simptome, istoric, examinare sau alte teste. Solicitați sfat dacă aveți nelămuriri."],["Die angegebene Dauer ist eine Produktschätzung und keine Garantie für jede Bestellung.","Bereitstellung und fachliche Prüfung müssen beim einzelnen Test genannt sein; nicht jeder Test umfasst eine Beratung.","Ein Ergebnis muss eventuell zusammen mit Beschwerden, Vorgeschichte, Untersuchung oder weiteren Tests bewertet werden. Holen Sie bei Unsicherheit fachlichen Rat ein."])},
    whyChoose:{eyebrow:t("Por qué Global Health","De ce Global Health","Warum Global Health"),title:t("Un catálogo por país","Un catalog pentru fiecare țară","Ein länderbezogener Testkatalog"),items:t(["Solo pruebas activas del país seleccionado","Precio y moneda configurados","Se respeta el estado de existencias","Muestra y plazo cuando están disponibles","Información y preguntas específicas en cada producto","Carrito y pago seguros"],["Numai teste active pentru țara selectată","Prețul și moneda configurate","Statutul stocului este respectat","Proba și termenul când sunt disponibile","Informații și întrebări specifice produsului","Coș și plată securizate"],["Nur aktive Tests für das gewählte Land","Aktuell hinterlegter Preis und Währung","Bestand wird vor Bestellung berücksichtigt","Probenart und Ergebnisdauer, sofern verfügbar","Testspezifische Angaben und häufige Fragen","Sicherer Warenkorb und Bestellvorgang"])},
    importantInformation:{eyebrow:t("Limitaciones importantes","Limitări importante","Wichtige Einschränkungen"),title:t("Una prueba no sustituye la atención urgente o completa","Un test nu înlocuiește îngrijirea urgentă sau completă","Ein Test ersetzt keine Notfall- oder umfassende Versorgung"),paragraphs:t(["No pida una prueba en línea si necesita una valoración de emergencia. Contacte con el servicio de emergencias local.","Un resultado normal no descarta todas las afecciones y uno anómalo no establece por sí solo un diagnóstico.","Recogida, disponibilidad, procesamiento, entrega, plazo y seguimiento varían por prueba y país. Consulte el producto concreto.","Ante síntomas nuevos, graves, preocupantes o que empeoran, solicite valoración clínica en vez de basarse solo en un resultado."],["Nu comandați online un test dacă aveți nevoie de evaluare de urgență. Contactați serviciul local de urgență.","Un rezultat normal nu exclude toate afecțiunile, iar unul anormal nu stabilește singur diagnosticul.","Recoltarea, disponibilitatea, procesarea, livrarea, termenul și monitorizarea variază după test și țară. Consultați produsul.","Pentru simptome noi, severe, îngrijorătoare sau în agravare, solicitați evaluare clinică în loc să vă bazați doar pe rezultat."],["Bestellen Sie keinen Online-Test, wenn Sie eine Notfallabklärung benötigen. Wenden Sie sich an den örtlichen Notdienst.","Ein unauffälliges Ergebnis schließt nicht jede Erkrankung aus; ein auffälliges Ergebnis stellt allein keine Diagnose.","Entnahme, Verfügbarkeit, Verarbeitung, Lieferung, Dauer und Nachsorge unterscheiden sich nach Test und Land. Beachten Sie die Produktangaben.","Lassen Sie neue, starke, zunehmende oder besorgniserregende Beschwerden fachlich abklären, statt sich nur auf ein Testergebnis zu verlassen."])},
    faq:t([["¿Qué pruebas hay en mi país?","Las tarjetas muestran las pruebas activas del país. Si no aparecen, no hay catálogo activo."],["¿Qué muestra necesito?","Consulte el tipo y las instrucciones completas antes de pedir."],["¿Cuánto tardan los resultados?","El plazo estimado aparece cuando está disponible; puede variar y no es un servicio de urgencias."],["¿Cómo recibiré los resultados?","Depende de la prueba. Siga la información del producto y pedido."],["¿Todas incluyen revisión clínica?","No. Solo está incluida si los datos de la prueba lo dicen expresamente."],["¿Puede sustituir una consulta?","No. Ninguna prueba sustituye la valoración de síntomas, antecedentes y demás información clínica."]],[["Ce teste sunt disponibile în țara mea?","Cardurile arată testele active. Dacă nu apar, nu există catalog activ."],["Ce probă trebuie să furnizez?","Verificați tipul și instrucțiunile complete înainte de comandă."],["Cât durează rezultatele?","Termenul estimat apare când este disponibil; poate varia și nu este serviciu de urgență."],["Cum primesc rezultatele?","Depinde de test. Urmați informațiile produsului și comenzii."],["Toate includ evaluare clinică?","Nu. Este inclusă numai dacă detaliile testului spun explicit acest lucru."],["Poate înlocui o consultație?","Nu. Niciun test nu înlocuiește evaluarea simptomelor, istoricului și altor informații clinice."]],[["Welche Tests gibt es in meinem Land?","Die Karten zeigen aktive Tests des Landes. Ohne Karten gibt es derzeit keinen aktiven Katalog."],["Welche Probe muss ich abgeben?","Prüfen Sie Probenart und vollständige Anleitung vor der Bestellung."],["Wie lange dauern Ergebnisse?","Die Schätzung wird, sofern verfügbar, angezeigt; sie kann abweichen und ist kein Notfalldienst."],["Wie erhalte ich Ergebnisse?","Das ist testspezifisch. Befolgen Sie Produkt- und Bestellhinweise."],["Enthält jeder Test eine fachliche Prüfung?","Nein. Sie gilt nur als enthalten, wenn die Testangaben dies ausdrücklich nennen."],["Kann ein Test eine Sprechstunde ersetzen?","Nein. Kein einzelner Test ersetzt die Bewertung von Beschwerden, Vorgeschichte und weiteren klinischen Informationen."]]).map(([question,answer])=>({question,answer})),
    emptyState:{title:t("Actualmente no hay pruebas disponibles","În prezent nu sunt disponibile teste","Derzeit sind keine Gesundheitstests verfügbar"),body:t(`Actualmente no hay pruebas activas que puedan pedirse en ${c.countryName}.`,`În prezent nu există teste active care pot fi comandate în ${c.countryName}.`,`Derzeit können in ${c.countryName} keine aktiven Gesundheitstests bestellt werden.`)},
  };
};

const get = (locale: Locale, kind: "specialist" | "tests", context: Context) => kind === "specialist" ? specialist(locale, context) : tests(locale, context);
export const getEsServiceHubContent = (kind: "specialist" | "tests", context: Context) => get("es", kind, context);
export const getRoServiceHubContent = (kind: "specialist" | "tests", context: Context) => get("ro", kind, context);
export const getDeServiceHubContent = (kind: "specialist" | "tests", context: Context) => get("de", kind, context);
