// Offline evidence and exact candidates. Existing native FAQs are updated, never replaced as a set.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {hash} from '../../backend/scripts/prepare-romania-seo.mjs';
const root='seo/brazil', read=p=>JSON.parse(fs.readFileSync(`${root}/${p}`));
const write=(p,v)=>fs.writeFileSync(`${root}/${p}`,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const csv=(p,rows)=>{assert(rows.length);const keys=[...new Set(rows.flatMap(Object.keys))],cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';write(p,[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\n')+'\n');};
fs.mkdirSync(`${root}/content-briefs`,{recursive:true});
const pages=read('raw/public-inventory-2026-09-13.json'),storage=read('raw/storage-preflight-2026-09-13.json').data;
const type=p=>{const a=new URL(p.url).pathname.split('/');return a[3]==='services'?'service':a[3]==='doctors'&&a[4]?'doctor':a[3]==='blog'&&a[4]?'article':a[3]==='tools'?'tool':a[3]??'home';};
const source=p=>{const a=new URL(p.url).pathname.split('/'),file=`raw/api/${a[3]}-${a[4]}-${p.locale.toUpperCase()}.json`,r=read(file);return{file,s:r.data.service??r.data.doctor};};
const scheduling={pt:'Confira os horários disponíveis antes de agendar. A consulta é por vídeo, em português, inglês ou espanhol.',en:'Check available appointments before booking. Video consultations are available in Portuguese, English or Spanish.',es:'Consulta los horarios disponibles antes de reservar. La consulta es por vídeo, en portugués, inglés o español.'};
const descriptions={
 'consulta-clinica-online':['Converse com um clínico geral por vídeo sobre sintomas e cuidados de saúde. Consulte os horários e o preço antes de agendar.','Discuss symptoms and general health with a doctor by video. Check appointment times and the price before booking.','Habla por vídeo con un médico general sobre síntomas y cuidados de salud. Consulta los horarios y el precio antes de reservar.'],
 'solicitacao-exames-online':['Converse com um médico por vídeo sobre a necessidade de exames. A solicitação depende da avaliação clínica. Confira horários e preço.','Discuss whether you need tests with a doctor by video. Any test request depends on the clinical assessment. Check times and price.','Consulta por vídeo si necesitas pruebas médicas. La solicitud depende de la valoración clínica. Revisa los horarios y el precio.'],
 'atestado-medico-online':['Agende uma avaliação médica por vídeo. A emissão de atestado depende da avaliação clínica; a consulta não garante um documento ou sua aceitação.','Book a medical assessment by video. A medical certificate depends on the assessment; booking does not guarantee a document or its acceptance.','Reserva una valoración médica por vídeo. La emisión de un certificado depende de la valoración; no se garantiza el documento ni su aceptación.'],
 'pediatria-online':['Consulta por vídeo para crianças e adolescentes com médico de família. Confira horários e preço. Não é uma consulta com pediatra especialista.','Video care for children and adolescents with a family doctor. Check times and price. This is not a specialist pediatric appointment.','Consulta por vídeo para niños y adolescentes con un médico de familia. Revisa horarios y precio. No es una consulta con un pediatra especialista.']
};
const faqCopy={
 acceptance:['A consulta não garante a emissão de um atestado nem sua aceitação. O médico avalia a necessidade do documento. Confirme com o destinatário os requisitos aplicáveis ao seu caso.','A consultation does not guarantee a medical certificate or its acceptance. The doctor assesses whether a document is appropriate. Check the requirements with its recipient.','La consulta no garantiza la emisión de un certificado ni su aceptación. El médico valora si corresponde emitirlo. Consulta los requisitos con el destinatario.'],
 timing:['A emissão depende da avaliação médica. Se houver indicação, confirme com o médico como e quando o documento será disponibilizado. Não há prazo garantido nesta página.','Issuance depends on the medical assessment. If a document is appropriate, confirm how and when it will be provided with the doctor. This page does not guarantee a deadline.','La emisión depende de la valoración médica. Si corresponde, confirma con el médico cómo y cuándo recibirás el documento. Esta página no garantiza un plazo.'],
 refusal:['Peça ao destinatário que explique o motivo da recusa e os requisitos exigidos. Se precisar, procure orientação jurídica sobre o seu caso. A consulta não garante aceitação pelo empregador.','Ask the recipient to explain the refusal and its requirements. Seek legal advice about your circumstances if needed. The consultation does not guarantee employer acceptance.','Pide al destinatario que explique el rechazo y sus requisitos. Si lo necesitas, busca asesoramiento jurídico sobre tu caso. La consulta no garantiza la aceptación del empleador.'],
 tests:['O médico avalia se os exames são necessários. Antes de agendar a coleta ou o exame, confirme com o laboratório ou a clínica os requisitos do pedido e os custos.','The doctor assesses whether tests are needed. Before booking a test, confirm the request requirements and costs with the laboratory or clinic.','El médico valora si necesitas pruebas. Antes de reservarlas, confirma los requisitos de la solicitud y los costes con el laboratorio o la clínica.'],
 followup:['Você pode verificar a agenda para uma nova consulta e conversar sobre os resultados. No momento, o catálogo do Brasil lista o Dr. Renato Sarmento. Confira o preço antes de agendar.','You can check the schedule for another consultation to discuss results. The Brazil catalogue currently lists Dr. Renato Sarmento. Check the price before booking.','Puedes consultar la agenda para otra consulta sobre tus resultados. El catálogo de Brasil muestra actualmente al Dr. Renato Sarmento. Revisa el precio antes de reservar.']
};
const drafts=[],coverage=[],supply=[];
for(const p of pages.filter(p=>['service','doctor'].includes(type(p)))){
 const {file,s}=source(p),i=['pt','en','es'].indexOf(p.locale);assert(i>=0);const before={},after={},faqPatches=[];
 const set=(k,v)=>{if(v!==s[k]){before[k]=s[k];after[k]=v;}};
 const native=s.faqs??[];
 // Source bodies contain no native FAQ migration candidates; inspect embedded headings separately.
 const embeddedHeads=[...(s.detailBody??s.bio??'').matchAll(/<h[23][^>]*>\s*(?:Perguntas frequentes|Frequently asked questions|Preguntas frecuentes|FAQ)\s*<\/h[23]>/gi)];
 coverage.push({url:p.url,locale:p.locale,resolved_locale:s.resolvedLocale,native_api:native.length,native_html:p.faqs.length,schema:p.schemaFaqCount,embedded_sections:embeddedHeads.length,embedded_questions:embeddedHeads.length?'verify separately':0,equivalent:JSON.stringify(p.faqs)===JSON.stringify(p.schemaFaqs),source:file,source_fingerprint:hash(s)});
 assert.equal(native.length,p.faqs.length,p.url);
 const patch=(order,key)=>{const f=native.find(f=>f.sortOrder===order);assert(f);faqPatches.push({id:f.id,before:{question:f.question,answer:f.answer},after:{question:f.question,answer:faqCopy[key][i]}});};
 if(type(p)==='service'){
  supply.push({url:p.url,locale:p.locale,service:s.slug,kind:s.kind,bookability:s.bookability.state,next_available_at:s.bookability.nextAvailableAt,assigned_doctor_ids:s.assignedDoctorIds.join('|'),consultation_languages:'Portuguese|English|Spanish',registration:'CFM regular PA11426/SP170837; family medicine RQE8822 in PA only',scope:'GENERAL; no specialist service expansion',source:file});
  set('seoTitle',s.seoTitle.replace(/\s*\|\s*(Mesmo Dia|Same Day|Mismo Día)$/i,''));
  set('heroTitle',s.heroTitle?.replace(/,?\s*(Mesmo Dia|Same Day|Mismo Día)$/i,'').trim());
  const desc=descriptions[s.slug]?.[i];
  if(desc)set('seoDescription',desc);
  else {const topic=s.name;set('seoDescription',i===0?`${topic}: consulta por vídeo com médico de família. Confira a agenda, o preço e os limites do atendimento antes de reservar.`:i===1?`${topic}: video consultation with a family doctor. Check appointments, price and care limitations before booking.`:`${topic}: consulta por vídeo con un médico de familia. Revisa la agenda, el precio y los límites de la atención antes de reservar.`);}
  if(s.slug==='consulta-clinica-online'){set('heroDescription',scheduling[p.locale]);patch(1,'acceptance');}
  if(s.slug==='atestado-medico-online'){set('seoTitle',['Atestado médico: avaliação online | Global Health Brasil','Medical certificate assessment | Global Health Brazil','Valoración para certificado médico | Global Health Brasil'][i]);set('heroTitle',['Atestado médico: avaliação por vídeo','Medical certificate: video assessment','Certificado médico: valoración por vídeo'][i]);set('heroDescription',descriptions[s.slug][i]);patch(0,'acceptance');patch(3,'timing');patch(5,'refusal');}
  if(s.slug==='solicitacao-exames-online'){patch(0,'tests');patch(5,'followup');set('heroDescription',descriptions[s.slug][i]);}
  if(s.slug==='pediatria-online'){set('seoTitle',['Saúde da criança: médico de família online | Brasil','Child health: family doctor online | Brazil','Salud infantil: médico de familia online | Brasil'][i]);set('heroTitle',['Saúde da criança e adolescente com médico de família','Child and adolescent health with a family doctor','Salud infantil y adolescente con un médico de familia'][i]);}
 }else{
  set('seoDescription',[`Agende uma consulta por vídeo com o Dr. Renato Sarmento. Atendimento em português, inglês ou espanhol. Confira os horários disponíveis.`,`Book a video consultation with Dr. Renato Sarmento in Portuguese, English or Spanish. Check available appointments before booking.`,`Reserva una consulta por vídeo con el Dr. Renato Sarmento en portugués, inglés o español. Consulta los horarios disponibles.`][i]);
  const f=native.find(f=>f.sortOrder===4);assert(f);faqPatches.push({id:f.id,before:{question:f.question,answer:f.answer},after:{question:f.question,answer:scheduling[p.locale]}});
 }
 if(Object.keys(after).length||faqPatches.length){const d={key:`${type(p)}:${s.slug}`,url:p.url,id:s.id,slug:s.slug,locale:p.locale,source:file,sourceFingerprint:hash(s),before,after,faqPatches,addedFaqs:[],hold:'',status:'unapproved local candidate',retained:'Other FAQ answers and body/biography retained as existing copy; not newly clinically verified'};d.payloadSha256=hash(d);drafts.push(d);}
}
const priority=['solicitacao-exames-online','consulta-clinica-online','renovacao-receita-online','atestado-medico-online','dr-renato-sarmento'];
drafts.sort((a,b)=>(priority.includes(a.slug)?priority.indexOf(a.slug):99)-(priority.includes(b.slug)?priority.indexOf(b.slug):99)||a.slug.localeCompare(b.slug)||a.locale.localeCompare(b.locale));
for(const p of pages.filter(p=>type(p)==='faq'))coverage.push({url:p.url,locale:p.locale,native_api:'code-owned country groups',native_html:'tab renderer; not details',schema:p.schemaFaqCount,embedded_sections:0,embedded_questions:0,equivalent:'same code-owned groups feed tabs/schema; PT browser checked',source:'frontend/locales/{en,pt}/faq-markets.json',source_fingerprint:p.sha256});
write('content-briefs/exact-drafts.json',drafts);csv('faq-coverage.csv',coverage);csv('doctor-service-language-matrix.csv',supply);
const gsc={};for(const period of ['current','previous']){const r=read(`raw/gsc-pages-${period}-2026-09-13.json`);assert.equal(r.hasMore,false);gsc[period]=r.rows;}
const q=read('raw/gsc-query-page-current-2026-09-13.json');assert.equal(q.hasMore,false);
const performance=(rows,p)=>rows.find(r=>r.keys[0]===p.url)??{clicks:0,impressions:0};
const matrix=pages.map(p=>{const d=drafts.find(d=>d.url===p.url),t=type(p),f=coverage.find(f=>f.url===p.url);let disposition=d?'change':'retain with evidence',reason=d?'Remove unsupported availability/document promises; exact packet requires clinical review':'Observed live HTTP/canonical/metadata; no justified rewrite in focused commercial batch; body not newly verified';
 if(['article','legal'].includes(t)||p.url.includes('/legal/')){disposition='hold';reason='Existing publication retained; genuine clinical/native review or Brazilian legal approval needed for body changes';}
 if(['home','pricing','dr-renato','faq'].includes(t)){disposition='verify further';reason=t==='faq'?'Existing authored FAQ integration; document signing/Atesta operational fact unresolved':t==='pricing'?'Plan offer and individual consultation pricing must be reconciled with business scope':t==='home'?'Registados and specialist claim require exact homepage source revision':'Dedicated clinician landing page requires separate storage ownership and content review';}
 return{url:p.url,locale:p.locale,page_type:t,discovery:p.discovery,status:p.status,disposition,reason,keyword_evidence:q.rows.filter(r=>r.keys[1]===p.url).sort((a,b)=>b.impressions-a.impressions).slice(0,3).map(r=>`${r.keys[0]} (${r.impressions} impressions)`).join(' | '),current_clicks:performance(gsc.current,p).clicks,current_impressions:performance(gsc.current,p).impressions,existing_title:p.title,proposed_title:d?.after.seoTitle??p.title,existing_description:p.description,proposed_description:d?.after.seoDescription??p.description,existing_h1:p.h1.join('|'),proposed_h1:d?.after.heroTitle??p.h1.join('|'),native_faqs:f?.native_api??p.faqs.length,embedded_faq_sections:f?.embedded_sections??'not separately parsed',schema_faqs:p.schemaFaqCount,source_fingerprint:d?.sourceFingerprint??p.sha256,review_status:d?'required; no approval':'not newly clinically verified',implementation_status:d?'prepared locally; not applied':'unchanged',canonical:p.canonical,robots:p.robots};});
csv('page-by-page-completion-matrix.csv',matrix);csv('target-page-inventory.csv',matrix.map(({url,locale,page_type,discovery,status,canonical,robots})=>({url,locale,page_type,discovery,status,canonical,robots})));
csv('05-url-keyword-map.csv',matrix.map(r=>({url:r.url,locale:r.locale,type:r.page_type,evidence:r.keyword_evidence,ownership:r.page_type==='service'?'commercial':r.page_type==='article'||r.page_type==='tool'?'informational':'navigation/support',editorial_label:r.existing_h1,disposition:r.disposition})));
csv('04-content-gap.csv',matrix.filter(r=>r.disposition!=='retain with evidence').map(({url,locale,disposition,reason,proposed_title})=>({url,locale,disposition,reason,proposed_title})));
const metrics=read('raw/keyword-metrics-2026-09-13.json').keywords;
csv('03-keyword-master.csv',metrics.map(k=>({...k,location:2076,language:'pt',source:'OpenSEO Brazil 2026-09-13',scope:k.main_intent==='informational'?'Map by observed SERP and page intent; no new article authorization':'Existing staffed service only'})).concat([{keyword:'consulta online saúde masculina',location:2076,language:'pt',source:'Requested but not returned; unavailable'}]));
csv('keyword-exclusions.csv',q.rows.filter(r=>/global|gratis|grátis|gratuito|sus|inss|emerg.ncia/i.test(r.keys[0])).map(r=>({query:r.keys[0],url:r.keys[1],clicks:r.clicks,impressions:r.impressions,classification:/myglobalhealth|my global health/i.test(r.keys[0])?'potential relevant brand; confirm identity':/global/i.test(r.keys[0])?'brand ambiguity/collision; excluded from qualified demand':'unsupported free/public-system/emergency intent; excluded'})));
csv('clinical-review-register.csv',drafts.map(d=>({url:d.url,key:d.key,payload_sha256:d.payloadSha256,status:'PENDING',reviewer_doctor_id:'',reviewer_name:'',reviewed_at:'',evidence:'',dependency:'Exact clinical/native review; Brazil review-age policy; production authorization'})));
csv('doctor-profile-fact-register.csv',[{doctor_id:storage.doctors[0].id,claim:'Name and registrations',status:'verified CFM named search',evidence:'raw/registry-check-2026-09-13.md',finding:'Renato Ziviani Sarmento; PA11426/SP170837 regular'},{doctor_id:storage.doctors[0].id,claim:'Family and Community Medicine RQE',status:'verified in PA only',evidence:'CFM named search',finding:'RQE8822 in PA; SP says no specialty registered'},{doctor_id:storage.doctors[0].id,claim:'Graduation',status:'verified CFM',evidence:'CFM named search',finding:'Centro Universitário do Estado do Pará, 2013'},{doctor_id:storage.doctors[0].id,claim:'Other degrees, palliative claims, employment, superlatives, company relationship',status:'unverified; retained existing debt',evidence:'Stored/public biography alone insufficient',finding:'Obtain primary degree/employment evidence and clinician confirmation before asserting new verification'}]);
const sum=rows=>rows.reduce((a,r)=>({clicks:a.clicks+r.clicks,impressions:a.impressions+r.impressions}),{clicks:0,impressions:0});
const totals={};for(const [period,rows]of Object.entries(gsc)){totals[period]={total:sum(rows),segments:Object.fromEntries(['service','doctor','article','tool','other'].map(t=>[t,sum(rows.filter(r=>{const p=pages.find(p=>p.url===r.keys[0]);const typ=p?type(p):'other';return (['service','doctor','article','tool'].includes(typ)?typ:'other')===t;}))]))};}write('raw/performance-summary.json',totals);
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
write('content-briefs/review-packet.html',`<!doctype html><meta charset="utf-8"><title>Brazil exact review packet</title><style>body{max-width:1000px;margin:40px auto;font:16px system-ui;line-height:1.5}pre{white-space:pre-wrap;background:#f3f3f3;padding:16px}section{border-top:1px solid #aaa;margin-top:32px}</style><h1>Brazil: exact local candidates</h1><p>No clinical approval or production publication. Retained bodies and unmodified answers are not newly verified. Primary sources and known holds: ../07-technical-audit.md and ../doctor-profile-fact-register.csv.</p>${drafts.map(d=>`<section><h2>${esc(d.url)}</h2><p>Payload SHA-256: ${d.payloadSha256}</p><h3>Before</h3><pre>${esc(JSON.stringify({fields:d.before,faqs:d.faqPatches.map(f=>f.before)},null,2))}</pre><h3>After</h3><pre>${esc(JSON.stringify({fields:d.after,faqs:d.faqPatches.map(f=>f.after)},null,2))}</pre><p>${esc(d.retained)}</p></section>`).join('')}`);
assert.equal(new Set(matrix.map(r=>r.url)).size,pages.length);
console.log(JSON.stringify({urls:pages.length,drafts:drafts.length,faqPatches:drafts.reduce((n,d)=>n+d.faqPatches.length,0),totals,dispositions:matrix.reduce((a,r)=>(a[r.disposition]=(a[r.disposition]??0)+1,a),{})}));
