ALTER TABLE "Doctor"
ADD COLUMN IF NOT EXISTS "seoTitle" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescription" TEXT,
ADD COLUMN IF NOT EXISTS "editorialChecklist" JSONB;

ALTER TABLE "Service"
ADD COLUMN IF NOT EXISTS "seoTitle" TEXT,
ADD COLUMN IF NOT EXISTS "seoDescription" TEXT,
ADD COLUMN IF NOT EXISTS "editorialChecklist" JSONB;

ALTER TABLE "BlogPost"
ADD COLUMN IF NOT EXISTS "reviewerDisplayName" TEXT,
ADD COLUMN IF NOT EXISTS "lastReviewedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "editorialChecklist" JSONB;

ALTER TABLE "ContentPage"
ADD COLUMN IF NOT EXISTS "editorialChecklist" JSONB;
