import type { IrelandGeneralServiceLocalizedSeoUpdate } from "./ireland-general-service-keywords.js";

/** Localized completion payload for the ten owner-approved Ireland GENERAL pages. */
export const irelandGeneralServiceLocalizedCompletionSeoUpdates = [
  {
    slug: "acute-medical-consultation",
    locale: "PT",
    seoTitle: "Consulta Médica Online no Mesmo Dia na Irlanda | Médico Online",
    seoDescription: "Marque uma consulta médica online no mesmo dia na Irlanda para sintomas não urgentes adequados, avaliação clínica e orientação sobre os próximos passos.",
    heroTitle: "Consulta Médica Online no Mesmo Dia na Irlanda",
  },
  {
    slug: "aesthetic-medicine-consultation",
    locale: "PT",
    seoTitle: "Consulta de Medicina Estética na Irlanda | Cuidados Pré e Pós",
    seoDescription: "Marque uma consulta online de medicina estética na Irlanda para aconselhamento independente antes do procedimento ou avaliação médica de preocupações adequadas após o procedimento.",
    heroTitle: "Consulta Online de Medicina Estética na Irlanda",
  },
  {
    slug: "chronic-disease-consultation",
    locale: "PT",
    seoTitle: "Consulta Online de Doença Crónica na Irlanda | Cuidados Contínuos",
    seoDescription: "Marque uma consulta online de doença crónica na Irlanda para revisão estruturada de uma condição diagnosticada, segurança do tratamento e planeamento de cuidados contínuos.",
    heroTitle: "Consulta Online de Doença Crónica na Irlanda",
  },
  {
    slug: "mens-health-consultation",
    locale: "PT",
    seoTitle: "Consulta de Saúde Masculina Online na Irlanda | Médico Confidencial",
    seoDescription: "Marque uma consulta confidencial de saúde masculina online na Irlanda para avaliação de questões sexuais, hormonais, da próstata ou de saúde geral do homem.",
    heroTitle: "Consulta de Saúde Masculina Online na Irlanda",
  },
  {
    slug: "musculoskeletal-pain-assessment",
    locale: "PT",
    seoTitle: "Avaliação Musculoesquelética Online na Irlanda | Dor e Articulações",
    seoDescription: "Marque uma avaliação musculoesquelética online na Irlanda para dores adequadas nas costas ou articulações, ciática ou lesões dos tecidos moles e orientação clínica.",
    heroTitle: "Avaliação Musculoesquelética e da Dor Online na Irlanda",
  },
  {
    slug: "paediatric-consultation",
    locale: "PT",
    seoTitle: "Consulta Pediátrica Online na Irlanda | Médico para Crianças",
    seoDescription: "Marque uma consulta pediátrica online na Irlanda para problemas não urgentes adequados de bebés, crianças ou adolescentes e orientação sobre encaminhamento quando necessário.",
    heroTitle: "Consulta Pediátrica Online na Irlanda",
  },
  {
    slug: "second-opinion-consultation",
    locale: "PT",
    seoTitle: "Segunda Opinião Médica Online na Irlanda | Avaliação Independente",
    seoDescription: "Marque uma segunda opinião médica online na Irlanda para revisão independente ao nível de medicina geral de diagnóstico, plano de tratamento, carta clínica ou resultado de exame.",
    heroTitle: "Segunda Opinião Médica Online na Irlanda",
  },
  {
    slug: "sick-certificate-ireland",
    locale: "PT",
    seoTitle: "Atestado Médico Online na Irlanda | Avaliação no Mesmo Dia",
    seoDescription: "Marque uma avaliação médica online para um atestado de doença na Irlanda. O documento só é emitido quando clinicamente adequado e não é garantido.",
    heroTitle: "Avaliação Online para Atestado Médico na Irlanda",
  },
  {
    slug: "travel-health-consultation",
    locale: "PT",
    seoTitle: "Consulta de Saúde do Viajante Online na Irlanda | Médico de Viagem",
    seoDescription: "Marque uma consulta de saúde do viajante online na Irlanda para avaliação de riscos do destino, orientação sobre vacinas, malária e planeamento antes da viagem.",
    heroTitle: "Consulta de Saúde do Viajante Online na Irlanda",
  },
  {
    slug: "womens-health-consultation",
    locale: "PT",
    seoTitle: "Consulta de Saúde da Mulher Online na Irlanda | Médico Confidencial",
    seoDescription: "Marque uma consulta confidencial de saúde da mulher online na Irlanda para avaliação de menopausa, SOP, contraceção, questões hormonais ou reprodutivas.",
    heroTitle: "Consulta de Saúde da Mulher Online na Irlanda",
  },
  {
    slug: "acute-medical-consultation",
    locale: "ES",
    seoTitle: "Consulta Médica Online el Mismo Día en Irlanda | Médico Online",
    seoDescription: "Reserve una consulta médica online el mismo día en Irlanda para síntomas no urgentes adecuados, evaluación clínica y orientación sobre los próximos pasos.",
    heroTitle: "Consulta Médica Online el Mismo Día en Irlanda",
  },
  {
    slug: "aesthetic-medicine-consultation",
    locale: "ES",
    seoTitle: "Consulta de Medicina Estética en Irlanda | Atención Pre y Posprocedimiento",
    seoDescription: "Reserve una consulta online de medicina estética en Irlanda para asesoramiento independiente previo o evaluación médica de problemas adecuados después del procedimiento.",
    heroTitle: "Consulta Online de Medicina Estética en Irlanda",
  },
  {
    slug: "chronic-disease-consultation",
    locale: "ES",
    seoTitle: "Consulta Online de Enfermedad Crónica en Irlanda | Atención Continua",
    seoDescription: "Reserve una consulta online de enfermedad crónica en Irlanda para revisar una afección diagnosticada, la seguridad del tratamiento y el plan de atención continua.",
    heroTitle: "Consulta Online de Enfermedad Crónica en Irlanda",
  },
  {
    slug: "mens-health-consultation",
    locale: "ES",
    seoTitle: "Consulta de Salud Masculina Online en Irlanda | Médico Confidencial",
    seoDescription: "Reserve una consulta confidencial de salud masculina online en Irlanda para evaluar problemas sexuales, hormonales, prostáticos o de salud general masculina.",
    heroTitle: "Consulta de Salud Masculina Online en Irlanda",
  },
  {
    slug: "musculoskeletal-pain-assessment",
    locale: "ES",
    seoTitle: "Evaluación Musculoesquelética Online en Irlanda | Dolor y Articulaciones",
    seoDescription: "Reserve una evaluación musculoesquelética online en Irlanda para dolor de espalda o articulaciones, ciática o problemas adecuados de tejidos blandos y orientación clínica.",
    heroTitle: "Evaluación Musculoesquelética y del Dolor Online en Irlanda",
  },
  {
    slug: "paediatric-consultation",
    locale: "ES",
    seoTitle: "Consulta Pediátrica Online en Irlanda | Médico para Niños",
    seoDescription: "Reserve una consulta pediátrica online en Irlanda para problemas no urgentes adecuados de bebés, niños o adolescentes y orientación sobre derivación cuando sea necesaria.",
    heroTitle: "Consulta Pediátrica Online en Irlanda",
  },
  {
    slug: "second-opinion-consultation",
    locale: "ES",
    seoTitle: "Segunda Opinión Médica Online en Irlanda | Revisión Independiente",
    seoDescription: "Reserve una segunda opinión médica online en Irlanda para una revisión independiente a nivel de medicina general de un diagnóstico, tratamiento, carta clínica o resultado.",
    heroTitle: "Segunda Opinión Médica Online en Irlanda",
  },
  {
    slug: "sick-certificate-ireland",
    locale: "ES",
    seoTitle: "Certificado Médico Online en Irlanda | Evaluación el Mismo Día",
    seoDescription: "Reserve una evaluación médica online para solicitar un certificado de baja en Irlanda. Solo se emite cuando es clínicamente adecuado y no está garantizado.",
    heroTitle: "Evaluación Online para Certificado Médico en Irlanda",
  },
  {
    slug: "travel-health-consultation",
    locale: "ES",
    seoTitle: "Consulta de Salud del Viajero Online en Irlanda | Médico de Viaje",
    seoDescription: "Reserve una consulta de salud del viajero online en Irlanda para evaluar riesgos del destino y recibir orientación sobre vacunas, malaria y planificación previa al viaje.",
    heroTitle: "Consulta de Salud del Viajero Online en Irlanda",
  },
  {
    slug: "womens-health-consultation",
    locale: "ES",
    seoTitle: "Consulta de Salud Femenina Online en Irlanda | Médico Confidencial",
    seoDescription: "Reserve una consulta confidencial de salud femenina online en Irlanda para evaluar menopausia, SOP, anticoncepción y problemas hormonales o reproductivos.",
    heroTitle: "Consulta de Salud Femenina Online en Irlanda",
  },
  {
    slug: "acute-medical-consultation",
    locale: "CS",
    seoTitle: "Online konzultace s lékařem v Irsku ještě dnes | Lékař online",
    seoDescription: "Objednejte si online konzultaci s lékařem v Irsku ještě dnes kvůli vhodným neurgentním příznakům, klinickému posouzení a doporučení dalších kroků.",
    heroTitle: "Online konzultace s lékařem v Irsku ještě dnes",
  },
  {
    slug: "aesthetic-medicine-consultation",
    locale: "CS",
    seoTitle: "Konzultace estetické medicíny v Irsku | Péče před a po zákroku",
    seoDescription: "Objednejte si online konzultaci estetické medicíny v Irsku pro nezávislé rady před zákrokem nebo lékařské posouzení vhodných potíží po zákroku.",
    heroTitle: "Online konzultace estetické medicíny v Irsku",
  },
  {
    slug: "chronic-disease-consultation",
    locale: "CS",
    seoTitle: "Online konzultace chronického onemocnění v Irsku | Průběžná péče",
    seoDescription: "Objednejte si online konzultaci chronického onemocnění v Irsku pro strukturovanou kontrolu diagnostikované nemoci, bezpečnost léčby a plán další péče.",
    heroTitle: "Online konzultace chronického onemocnění v Irsku",
  },
  {
    slug: "mens-health-consultation",
    locale: "CS",
    seoTitle: "Online konzultace mužského zdraví v Irsku | Důvěrně s lékařem",
    seoDescription: "Objednejte si důvěrnou online konzultaci mužského zdraví v Irsku kvůli sexuálním, hormonálním, prostatickým nebo obecným zdravotním potížím.",
    heroTitle: "Online konzultace mužského zdraví v Irsku",
  },
  {
    slug: "musculoskeletal-pain-assessment",
    locale: "CS",
    seoTitle: "Online posouzení pohybového aparátu v Irsku | Bolest a klouby",
    seoDescription: "Objednejte si online posouzení pohybového aparátu v Irsku kvůli vhodné bolesti zad či kloubů, ischiasu nebo potížím měkkých tkání a dalšímu doporučení.",
    heroTitle: "Online posouzení pohybového aparátu a bolesti v Irsku",
  },
  {
    slug: "paediatric-consultation",
    locale: "CS",
    seoTitle: "Online dětská konzultace v Irsku | Lékař pro děti",
    seoDescription: "Objednejte si online dětskou konzultaci v Irsku kvůli vhodným neurgentním potížím kojenců, dětí nebo dospívajících a doporučení specialisty podle potřeby.",
    heroTitle: "Online dětská lékařská konzultace v Irsku",
  },
  {
    slug: "second-opinion-consultation",
    locale: "CS",
    seoTitle: "Online druhý lékařský názor v Irsku | Nezávislé posouzení",
    seoDescription: "Objednejte si online druhý lékařský názor v Irsku pro nezávislou kontrolu diagnózy, léčebného plánu, lékařské zprávy nebo výsledku vyšetření.",
    heroTitle: "Online druhý lékařský názor v Irsku",
  },
  {
    slug: "sick-certificate-ireland",
    locale: "CS",
    seoTitle: "Online pracovní neschopnost v Irsku | Lékařské posouzení dnes",
    seoDescription: "Objednejte si online lékařské posouzení pro potvrzení o pracovní neschopnosti v Irsku. Doklad se vydává jen při klinické vhodnosti a není zaručen.",
    heroTitle: "Online posouzení pro potvrzení o pracovní neschopnosti v Irsku",
  },
  {
    slug: "travel-health-consultation",
    locale: "CS",
    seoTitle: "Online konzultace cestovní medicíny v Irsku | Lékař na cesty",
    seoDescription: "Objednejte si online konzultaci cestovní medicíny v Irsku pro posouzení rizik destinace, doporučení očkování, malárie a plánování před cestou.",
    heroTitle: "Online konzultace cestovní medicíny v Irsku",
  },
  {
    slug: "womens-health-consultation",
    locale: "CS",
    seoTitle: "Online konzultace ženského zdraví v Irsku | Důvěrně s lékařem",
    seoDescription: "Objednejte si důvěrnou online konzultaci ženského zdraví v Irsku kvůli menopauze, PCOS, antikoncepci nebo hormonálním či reprodukčním potížím.",
    heroTitle: "Online konzultace ženského zdraví v Irsku",
  },
  {
    slug: "acute-medical-consultation",
    locale: "RO",
    seoTitle: "Consultație medicală online în aceeași zi în Irlanda | Medic online",
    seoDescription: "Programați o consultație medicală online în aceeași zi în Irlanda pentru simptome neurgente adecvate, evaluare clinică și recomandări privind pașii următori.",
    heroTitle: "Consultație medicală online în aceeași zi în Irlanda",
  },
  {
    slug: "aesthetic-medicine-consultation",
    locale: "RO",
    seoTitle: "Consultație de medicină estetică în Irlanda | Înainte și după procedură",
    seoDescription: "Programați o consultație online de medicină estetică în Irlanda pentru sfaturi independente înaintea procedurii sau evaluarea medicală a problemelor adecvate de după procedură.",
    heroTitle: "Consultație online de medicină estetică în Irlanda",
  },
  {
    slug: "chronic-disease-consultation",
    locale: "RO",
    seoTitle: "Consultație online pentru boli cronice în Irlanda | Îngrijire continuă",
    seoDescription: "Programați o consultație online pentru boli cronice în Irlanda, cu evaluarea structurată a afecțiunii diagnosticate, siguranța tratamentului și planificarea îngrijirii.",
    heroTitle: "Consultație online pentru boli cronice în Irlanda",
  },
  {
    slug: "mens-health-consultation",
    locale: "RO",
    seoTitle: "Consultație online pentru sănătatea bărbaților în Irlanda | Confidențial",
    seoDescription: "Programați o consultație confidențială online pentru sănătatea bărbaților în Irlanda privind probleme sexuale, hormonale, de prostată sau de sănătate generală.",
    heroTitle: "Consultație online pentru sănătatea bărbaților în Irlanda",
  },
  {
    slug: "musculoskeletal-pain-assessment",
    locale: "RO",
    seoTitle: "Evaluare musculo-scheletală online în Irlanda | Dureri și articulații",
    seoDescription: "Programați o evaluare musculo-scheletală online în Irlanda pentru dureri adecvate de spate sau articulații, sciatică ori probleme ale țesuturilor moi și recomandări clinice.",
    heroTitle: "Evaluare musculo-scheletală și a durerii online în Irlanda",
  },
  {
    slug: "paediatric-consultation",
    locale: "RO",
    seoTitle: "Consultație pediatrică online în Irlanda | Medic pentru copii",
    seoDescription: "Programați o consultație pediatrică online în Irlanda pentru probleme neurgente adecvate ale bebelușilor, copiilor sau adolescenților și recomandări de trimitere când este necesar.",
    heroTitle: "Consultație pediatrică online în Irlanda",
  },
  {
    slug: "second-opinion-consultation",
    locale: "RO",
    seoTitle: "A doua opinie medicală online în Irlanda | Evaluare independentă",
    seoDescription: "Programați o a doua opinie medicală online în Irlanda pentru evaluarea independentă a unui diagnostic, plan de tratament, scrisori medicale sau rezultat de analiză.",
    heroTitle: "A doua opinie medicală online în Irlanda",
  },
  {
    slug: "sick-certificate-ireland",
    locale: "RO",
    seoTitle: "Certificat medical online în Irlanda | Evaluare în aceeași zi",
    seoDescription: "Programați o evaluare medicală online pentru un certificat de concediu medical în Irlanda. Documentul se emite doar când este adecvat clinic și nu este garantat.",
    heroTitle: "Evaluare online pentru certificat medical în Irlanda",
  },
  {
    slug: "travel-health-consultation",
    locale: "RO",
    seoTitle: "Consultație de sănătate pentru călătorii în Irlanda | Medic online",
    seoDescription: "Programați o consultație online de sănătate pentru călătorii în Irlanda pentru riscurile destinației, recomandări despre vaccinuri, malarie și planificare înaintea călătoriei.",
    heroTitle: "Consultație online de sănătate pentru călătorii în Irlanda",
  },
  {
    slug: "womens-health-consultation",
    locale: "RO",
    seoTitle: "Consultație online pentru sănătatea femeilor în Irlanda | Confidențial",
    seoDescription: "Programați o consultație confidențială online pentru sănătatea femeilor în Irlanda privind menopauza, SOP, contracepția și probleme hormonale sau reproductive.",
    heroTitle: "Consultație online pentru sănătatea femeilor în Irlanda",
  },
  {
    slug: "acute-medical-consultation",
    locale: "DE",
    seoTitle: "Online-Arzttermin am selben Tag in Irland | Arzt online",
    seoDescription: "Buchen Sie einen Online-Arzttermin am selben Tag in Irland für geeignete, nicht dringende Beschwerden, eine klinische Beurteilung und Hinweise zu den nächsten Schritten.",
    heroTitle: "Online-Arzttermin am selben Tag in Irland",
  },
  {
    slug: "aesthetic-medicine-consultation",
    locale: "DE",
    seoTitle: "Online-Beratung für ästhetische Medizin in Irland | Vor- und Nachsorge",
    seoDescription: "Buchen Sie eine Online-Beratung für ästhetische Medizin in Irland für unabhängige Beratung vor einem Eingriff oder die ärztliche Beurteilung geeigneter Beschwerden danach.",
    heroTitle: "Online-Beratung für ästhetische Medizin in Irland",
  },
  {
    slug: "chronic-disease-consultation",
    locale: "DE",
    seoTitle: "Online-Beratung bei chronischer Erkrankung in Irland | Langzeitbetreuung",
    seoDescription: "Buchen Sie eine Online-Beratung bei chronischer Erkrankung in Irland zur strukturierten Kontrolle einer Diagnose, Behandlungssicherheit und weiteren Versorgungsplanung.",
    heroTitle: "Online-Beratung bei chronischer Erkrankung in Irland",
  },
  {
    slug: "mens-health-consultation",
    locale: "DE",
    seoTitle: "Online-Männergesundheitsberatung in Irland | Vertraulich beim Arzt",
    seoDescription: "Buchen Sie eine vertrauliche Online-Beratung zur Männergesundheit in Irland bei sexuellen, hormonellen, Prostata- oder allgemeinen Gesundheitsbeschwerden.",
    heroTitle: "Online-Beratung zur Männergesundheit in Irland",
  },
  {
    slug: "musculoskeletal-pain-assessment",
    locale: "DE",
    seoTitle: "Online-Beurteilung des Bewegungsapparats in Irland | Schmerz und Gelenke",
    seoDescription: "Buchen Sie eine Online-Beurteilung des Bewegungsapparats in Irland bei geeigneten Rücken- oder Gelenkschmerzen, Ischias oder Weichteilbeschwerden und zur weiteren Beratung.",
    heroTitle: "Online-Beurteilung von Bewegungsapparat und Schmerzen in Irland",
  },
  {
    slug: "paediatric-consultation",
    locale: "DE",
    seoTitle: "Online-Kindersprechstunde in Irland | Arzt für Kinder",
    seoDescription: "Buchen Sie eine Online-Kindersprechstunde in Irland für geeignete, nicht dringende Beschwerden bei Babys, Kindern oder Jugendlichen und Hinweise zur Überweisung bei Bedarf.",
    heroTitle: "Online-Kindersprechstunde in Irland",
  },
  {
    slug: "second-opinion-consultation",
    locale: "DE",
    seoTitle: "Ärztliche Zweitmeinung online in Irland | Unabhängige Beurteilung",
    seoDescription: "Buchen Sie eine ärztliche Zweitmeinung online in Irland zur unabhängigen hausärztlichen Prüfung einer Diagnose, eines Behandlungsplans, Arztbriefs oder Befunds.",
    heroTitle: "Ärztliche Zweitmeinung online in Irland",
  },
  {
    slug: "sick-certificate-ireland",
    locale: "DE",
    seoTitle: "Online-Krankmeldung in Irland | Ärztliche Beurteilung am selben Tag",
    seoDescription: "Buchen Sie eine ärztliche Online-Beurteilung für eine Krankmeldung in Irland. Eine Bescheinigung wird nur bei klinischer Eignung ausgestellt und ist nicht garantiert.",
    heroTitle: "Online-Beurteilung für eine Krankmeldung in Irland",
  },
  {
    slug: "travel-health-consultation",
    locale: "DE",
    seoTitle: "Online-Reisegesundheitsberatung in Irland | Reisemedizinischer Arzt",
    seoDescription: "Buchen Sie eine Online-Reisegesundheitsberatung in Irland zur Risikobewertung des Reiseziels, Impfberatung, Malariavorsorge und Planung vor der Reise.",
    heroTitle: "Online-Reisegesundheitsberatung in Irland",
  },
  {
    slug: "womens-health-consultation",
    locale: "DE",
    seoTitle: "Online-Frauengesundheitsberatung in Irland | Vertraulich beim Arzt",
    seoDescription: "Buchen Sie eine vertrauliche Online-Beratung zur Frauengesundheit in Irland bei Wechseljahren, PCOS, Verhütung sowie hormonellen oder reproduktiven Beschwerden.",
    heroTitle: "Online-Beratung zur Frauengesundheit in Irland",
  },
] as const satisfies readonly IrelandGeneralServiceLocalizedSeoUpdate[];
