// Exact editorial candidates, not published content. Locale order: RO, EN, CS, DE, ES, PT.
export const locales=['ro','en','cs','de','es','pt'];
export const shared={
 ro:[['În ce limbă pot discuta cu medicul?','Medicii disponibili pentru acest serviciu consultă în română și engleză. Verificați limba și ora disponibile la rezervare; limba în care citiți pagina nu schimbă limbile vorbite de medic.'],['Ce să pregătesc pentru consultație?','Notați simptomele, când au început și tratamentele pe care le urmați. Aveți la îndemână rezultatele și scrisorile medicale relevante, dacă există.'],['Ce se întâmplă dacă am nevoie de un consult fizic?','Medicul vă poate recomanda evaluare în persoană dacă discuția video și documentele nu sunt suficiente. Consultația online nu înlocuiește îngrijirea de urgență. Într-o urgență medicală, sunați la 112. Nu așteptați o programare online.']],
 en:[['Which languages can I use during the appointment?','The doctors available for this service consult in Romanian and English. Check the language and available time when booking; the language of this page does not change the languages the doctor speaks.'],['What should I have ready?','Note your symptoms, when they started and any treatment you take. Keep relevant test results and medical letters nearby if you have them.'],['What if I need a physical examination?','The doctor may recommend an in-person assessment if the video discussion and records are not enough. An online consultation does not replace emergency care. For a medical emergency, call 112. Do not wait for an online appointment.']],
 cs:[['V jakém jazyce probíhá konzultace?','Lékaři dostupní pro tuto službu konzultují v rumunštině a angličtině. Při rezervaci si ověřte jazyk a volný termín. Česká verze stránky neznamená, že lékař mluví česky.'],['Co si mám připravit?','Poznamenejte si příznaky, kdy začaly a jaké léky užíváte a jakou léčbu podstupujete. Pokud máte související výsledky vyšetření nebo lékařské zprávy, mějte je po ruce.'],['Co když potřebuji osobní vyšetření?','Pokud videohovor a zdravotní dokumentace nestačí, lékař může doporučit osobní vyšetření. Online konzultace nenahrazuje neodkladnou péči. V případě zdravotní nouze volejte 112. Nečekejte na online termín.']],
 de:[['In welcher Sprache findet der Termin statt?','Die für diese Leistung verfügbaren Ärzte beraten auf Rumänisch und Englisch. Prüfen Sie bei der Buchung die Sprache und den freien Termin. Eine deutsche Seite bedeutet nicht, dass der Arzt Deutsch spricht.'],['Was sollte ich bereithalten?','Notieren Sie Ihre Beschwerden, seit wann sie bestehen und welche Behandlungen Sie erhalten. Halten Sie vorhandene Befunde und Arztbriefe bereit, die damit zusammenhängen.'],['Was passiert, wenn eine körperliche Untersuchung nötig ist?','Wenn das Videogespräch und die Unterlagen nicht ausreichen, kann der Arzt eine Untersuchung vor Ort empfehlen. Eine Onlineberatung ersetzt keine Notfallversorgung. Rufen Sie bei einem medizinischen Notfall 112 an. Warten Sie nicht auf einen Onlinetermin.']],
 es:[['¿En qué idioma será la consulta?','Los médicos disponibles para este servicio atienden en rumano e inglés. Compruebe el idioma y la hora disponible al reservar. Que la página esté en español no significa que el médico hable español.'],['¿Qué debo preparar?','Anote sus síntomas, cuándo empezaron y los tratamientos que sigue. Tenga a mano los resultados y los informes médicos relacionados, si los tiene.'],['¿Y si necesito una exploración presencial?','El médico puede recomendar una valoración presencial si la videollamada y los informes no son suficientes. La consulta online no sustituye la atención de urgencias. En una emergencia médica, llame al 112. No espere a una cita online.']],
 pt:[['Em que língua decorre a consulta?','Os médicos disponíveis para este serviço dão consultas em romeno e inglês. Confirme a língua e o horário disponível ao marcar. A página em português não significa que o médico fale português.'],['O que devo preparar?','Anote os sintomas, quando começaram e os tratamentos que faz. Tenha consigo os resultados de exames e relatórios médicos relacionados, caso existam.'],['E se precisar de uma avaliação presencial?','O médico pode recomendar uma avaliação presencial se a videochamada e os documentos não forem suficientes. A consulta online não substitui os cuidados de urgência. Numa emergência médica, ligue 112. Não espere por uma consulta online.']]
};
// Each answer is restricted to the current Romania service's published scope.
export const services={
 'medic-online-romania':{
 labels:['Consultație medicală online','Online medical consultation','Online lékařská konzultace','Ärztliche Onlineberatung','Consulta médica online','Consulta médica online'],
 questions:['Pentru ce pot programa o consultație generală?','What can I discuss in a general consultation?','Co mohu řešit při všeobecné konzultaci?','Welche Anliegen kann ich allgemeinmedizinisch besprechen?','¿Qué puedo consultar con el médico general?','O que posso abordar numa consulta de medicina geral?'],
 answers:['Puteți discuta simptome recente, probleme de sănătate cunoscute sau nelămuriri despre tratament. Medicul analizează istoricul și vă explică dacă sunt potrivite recomandări, investigații sau un consult în persoană.','You can discuss recent symptoms, an existing health problem or questions about treatment. The doctor reviews your history and explains whether advice, tests or an in-person appointment would be appropriate.','Můžete probrat nové příznaky, známé zdravotní potíže nebo otázky k léčbě. Lékař projde vaši anamnézu a vysvětlí, zda jsou vhodná doporučení, další vyšetření nebo osobní návštěva.','Sie können neue Beschwerden, bestehende Erkrankungen oder Fragen zur Behandlung besprechen. Der Arzt prüft Ihre Vorgeschichte und erklärt, ob Empfehlungen, weitere Untersuchungen oder ein persönlicher Termin sinnvoll sind.','Puede consultar síntomas recientes, problemas de salud conocidos o dudas sobre su tratamiento. El médico revisa sus antecedentes y explica si convienen recomendaciones, pruebas o una consulta presencial.','Pode falar sobre sintomas recentes, problemas de saúde conhecidos ou dúvidas sobre o tratamento. O médico revê o historial e explica se são indicadas recomendações, exames ou uma consulta presencial.']},
 'a-doua-opinie-medicala':{
 labels:['A doua opinie medicală','Second medical opinion','Druhý lékařský názor','Zweite ärztliche Meinung','Segunda opinión médica','Segunda opinião médica'],
 questions:['Ce poate clarifica o a doua opinie?','What can a second opinion clarify?','Co může objasnit druhý lékařský názor?','Was kann eine zweite Meinung klären?','¿Qué puede aclarar una segunda opinión?','O que pode esclarecer uma segunda opinião?'],
 answers:['Puteți cere explicații despre un diagnostic, un tratament sau documentele medicale existente. Consultația generală vă ajută să înțelegeți întrebările rămase; dacă este necesară expertiza unui anumit specialist, medicul vă poate îndruma către acesta.','You can ask about a diagnosis, treatment or existing medical records. This general consultation helps clarify unanswered questions; if you need a particular specialist’s expertise, the doctor can recommend that assessment.','Můžete se zeptat na diagnózu, léčbu nebo dosavadní lékařské zprávy. Všeobecná konzultace pomůže objasnit nevyřešené otázky. Pokud je potřeba posouzení konkrétního specialisty, lékař vás na něj může odkázat.','Sie können Fragen zu einer Diagnose, Behandlung oder vorhandenen Befunden stellen. Diese allgemeine Beratung hilft, offene Fragen zu klären. Ist eine bestimmte Fachrichtung nötig, kann der Arzt eine entsprechende Beurteilung empfehlen.','Puede plantear dudas sobre un diagnóstico, un tratamiento o sus informes. Esta consulta general ayuda a aclarar preguntas pendientes; si necesita la valoración de un especialista concreto, el médico puede orientarle.','Pode colocar dúvidas sobre um diagnóstico, tratamento ou relatórios existentes. Esta consulta geral ajuda a esclarecer questões pendentes; se precisar de um especialista de determinada área, o médico pode recomendar essa avaliação.']},
 'boli-cronice-online':{
 labels:['Monitorizarea bolilor cronice','Chronic condition review','Kontrola chronických onemocnění','Beratung bei chronischen Erkrankungen','Seguimiento de enfermedades crónicas','Acompanhamento de doenças crónicas'],
 questions:['Este doar o consultație pentru reînnoirea rețetei?','Is this only a prescription renewal appointment?','Jde pouze o obnovení receptu?','Geht es nur um ein Folgerezept?','¿La consulta sirve solo para renovar una receta?','A consulta serve apenas para renovar uma receita?'],
 answers:['Nu. Puteți discuta evoluția simptomelor, rezultatele analizelor și felul în care tolerați tratamentul. Medicul stabilește dacă sunt necesare monitorizare, investigații sau o evaluare de specialitate; rețeta nu este un rezultat garantat.','No. You can review symptoms, test results and how you are tolerating treatment. The doctor decides whether monitoring, tests or specialist assessment are needed; a prescription is not guaranteed.','Ne. Můžete probrat vývoj příznaků, výsledky vyšetření a snášenlivost léčby. Lékař posoudí potřebu sledování, dalších vyšetření nebo odborné péče. Vystavení receptu není zaručeno.','Nein. Sie können Beschwerden, Untersuchungsergebnisse und die Verträglichkeit der Behandlung besprechen. Der Arzt entscheidet, ob Kontrollen, weitere Untersuchungen oder fachärztliche Betreuung nötig sind. Ein Rezept ist nicht garantiert.','No. Puede revisar los síntomas, los resultados y cómo tolera el tratamiento. El médico decide si necesita seguimiento, pruebas o valoración especializada; no se garantiza una receta.','Não. Pode rever os sintomas, os resultados dos exames e a tolerância ao tratamento. O médico avalia se precisa de acompanhamento, exames ou consulta de especialidade. A receita não está garantida.']},
 'caderea-parului-online':{
 labels:['Evaluare pentru căderea părului','Hair loss assessment','Posouzení vypadávání vlasů','Beratung bei Haarausfall','Valoración de la caída del cabello','Avaliação da queda de cabelo'],
 questions:['Ce informații ajută la evaluarea căderii părului?','What information helps assess hair loss?','Jaké informace pomohou při posouzení vypadávání vlasů?','Welche Angaben helfen bei Haarausfall?','¿Qué información ayuda a valorar la caída del cabello?','Que informações ajudam a avaliar a queda de cabelo?'],
 answers:['Spuneți când a început, dacă afectează anumite zone și ce tratamente ați încercat. Istoricul familial, bolile recente și medicația pot ajuta medicul să decidă dacă sunt necesare analize sau un consult dermatologic.','Explain when it started, whether it affects particular areas and what you have tried. Family history, recent illness and medicines can help the doctor decide whether tests or a dermatology appointment are needed.','Popište, kdy potíže začaly, zda se týkají určitých míst a co jste již vyzkoušeli. Rodinná anamnéza, nedávné nemoci a léky mohou pomoci rozhodnout o vyšetřeních nebo návštěvě dermatologa.','Beschreiben Sie Beginn, betroffene Stellen und bisherige Behandlungen. Familiäre Vorbelastung, kürzliche Erkrankungen und Medikamente helfen bei der Entscheidung, ob Tests oder ein Hautarzttermin nötig sind.','Explique cuándo empezó, qué zonas afecta y qué ha probado. Los antecedentes familiares, las enfermedades recientes y los medicamentos ayudan a decidir si necesita pruebas o una consulta dermatológica.','Explique quando começou, que zonas afeta e o que já experimentou. O historial familiar, doenças recentes e medicamentos podem ajudar a decidir se são necessários exames ou uma consulta de dermatologia.']},
 'consultatie-dermatologica':{
 labels:['Evaluare inițială a problemelor de piele','Initial skin assessment','Prvotní posouzení kožních potíží','Erste Einschätzung von Hautproblemen','Valoración inicial de problemas de piel','Avaliação inicial de problemas de pele'],
 questions:['Consultația este cu un medic dermatolog?','Is this appointment with a dermatologist?','Jde o konzultaci s dermatologem?','Ist dies ein Termin beim Hautarzt?','¿La consulta es con un dermatólogo?','A consulta é com um dermatologista?'],
 answers:['Acesta este un serviciu de medicină generală pentru evaluarea inițială a problemelor de piele. Medicul poate discuta simptomele și fotografiile disponibile și poate recomanda un dermatolog dacă este necesară o evaluare de specialitate.','This is a general medical service for an initial skin assessment. The doctor can discuss symptoms and available photographs, and recommend a dermatologist when specialist assessment is needed.','Jde o službu všeobecného lékařství pro prvotní posouzení kožních potíží. Lékař může probrat příznaky a dostupné fotografie a doporučit dermatologa, pokud je nutné odborné vyšetření.','Dies ist eine allgemeinmedizinische Ersteinschätzung von Hautproblemen. Der Arzt kann Beschwerden und vorhandene Fotos besprechen und bei Bedarf eine hautärztliche Untersuchung empfehlen.','Es un servicio de medicina general para una primera valoración de la piel. El médico puede revisar los síntomas y las fotografías disponibles y recomendar un dermatólogo si necesita atención especializada.','É um serviço de medicina geral para uma avaliação inicial da pele. O médico pode analisar os sintomas e fotografias disponíveis e recomendar dermatologia se for necessária uma avaliação especializada.']},
 'consultatie-neurologie':{
 labels:['Consultație de neurologie online','Online neurology consultation','Online neurologická konzultace','Neurologische Onlineberatung','Consulta de neurología online','Consulta de neurologia online'],
 questions:['Pot discuta rezultatele unor investigații neurologice?','Can I discuss neurological test results?','Mohu probrat výsledky neurologických vyšetření?','Kann ich neurologische Befunde besprechen?','¿Puedo consultar resultados de pruebas neurológicas?','Posso discutir resultados de exames neurológicos?'],
 answers:['Da. Puteți discuta rapoartele existente împreună cu simptomele și istoricul medical. Neurologul explică ce informații oferă acestea și dacă sunt necesare investigații suplimentare sau un consult în persoană.','Yes. You can discuss existing reports alongside your symptoms and medical history. The neurologist explains what the findings mean and whether further tests or an in-person assessment are needed.','Ano. Dosavadní zprávy můžete probrat spolu s příznaky a anamnézou. Neurolog vysvětlí nálezy a posoudí, zda potřebujete další vyšetření nebo osobní návštěvu.','Ja. Sie können vorhandene Befunde zusammen mit Ihren Beschwerden und Ihrer Vorgeschichte besprechen. Der Neurologe erklärt die Ergebnisse und ob weitere Untersuchungen oder ein persönlicher Termin nötig sind.','Sí. Puede comentar los informes junto con sus síntomas y antecedentes. El neurólogo explica los hallazgos y si necesita otras pruebas o una valoración presencial.','Sim. Pode discutir os relatórios existentes juntamente com os sintomas e o historial clínico. O neurologista explica os resultados e se precisa de mais exames ou de uma avaliação presencial.']},
 'consultatie-pediatrie':{
 labels:['Consultație cu medic pediatru online','Online pediatrician consultation','Online konzultace s pediatrem','Onlineberatung beim Kinderarzt','Consulta con pediatra online','Consulta com pediatra online'],
 questions:['Când poate fi utilă opinia unui pediatru?','When might a pediatrician’s opinion help?','Kdy může pomoci názor pediatra?','Wann kann eine kinderärztliche Einschätzung helfen?','¿Cuándo puede ayudar la opinión de un pediatra?','Quando pode ajudar a opinião de um pediatra?'],
 answers:['Puteți discuta simptome persistente sau recurente, evoluția după un tratament și întrebări despre dezvoltarea copilului. Pediatrul revizuiește istoricul și documentele disponibile și explică dacă este nevoie de investigații sau examinare fizică.','You can discuss persistent or recurring symptoms, progress after treatment and questions about your child’s development. The pediatrician reviews the history and available records, then explains whether tests or a physical examination are needed.','Můžete probrat přetrvávající či opakované příznaky, průběh po léčbě a otázky k vývoji dítěte. Pediatr projde anamnézu a dostupné zprávy a vysvětlí, zda je potřeba vyšetření nebo osobní prohlídka.','Sie können anhaltende oder wiederkehrende Beschwerden, den Verlauf nach einer Behandlung und Fragen zur Entwicklung Ihres Kindes besprechen. Der Kinderarzt prüft die Vorgeschichte und Unterlagen und erklärt den weiteren Untersuchungsbedarf.','Puede consultar síntomas persistentes o repetidos, la evolución tras un tratamiento y dudas sobre el desarrollo de su hijo. El pediatra revisa los antecedentes y los informes y explica si necesita pruebas o exploración física.','Pode abordar sintomas persistentes ou recorrentes, a evolução após tratamento e dúvidas sobre o desenvolvimento da criança. O pediatra revê o historial e os documentos e explica se são necessários exames ou avaliação presencial.']},
 'controlul-greutatii':{
 labels:['Consultație pentru controlul greutății','Medical weight management review','Lékařská konzultace ke kontrole hmotnosti','Ärztliche Beratung zum Gewicht','Consulta médica sobre el peso','Consulta médica sobre o peso'],
 questions:['Consultația include evaluarea cauzelor medicale?','Does the consultation consider medical causes?','Zohledňuje konzultace zdravotní příčiny?','Werden medizinische Ursachen berücksichtigt?','¿Se valoran posibles causas médicas?','São avaliadas possíveis causas médicas?'],
 answers:['Medicul discută evoluția greutății, tratamentele, somnul, alimentația și rezultatele existente. În funcție de situație, poate recomanda investigații, schimbări de obiceiuri sau evaluare de specialitate. Nu se poate promite un anumit rezultat de slăbire.','The doctor discusses weight changes, medicines, sleep, eating habits and existing results. Depending on your circumstances, they may recommend tests, changes to habits or specialist assessment. A particular amount of weight loss cannot be promised.','Lékař probere změny hmotnosti, léky, spánek, stravování a dostupné výsledky. Podle situace může doporučit vyšetření, úpravu návyků nebo odborné posouzení. Konkrétní úbytek hmotnosti nelze slíbit.','Der Arzt bespricht Gewichtsverlauf, Medikamente, Schlaf, Ernährung und vorhandene Befunde. Je nach Situation kommen Untersuchungen, Änderungen von Gewohnheiten oder fachärztliche Beratung infrage. Ein bestimmter Gewichtsverlust lässt sich nicht versprechen.','El médico revisa los cambios de peso, los medicamentos, el sueño, la alimentación y los resultados disponibles. Puede recomendar pruebas, cambios de hábitos o valoración especializada. No se puede prometer una pérdida de peso concreta.','O médico revê a evolução do peso, medicamentos, sono, alimentação e resultados existentes. Pode recomendar exames, alterações de hábitos ou avaliação especializada. Não é possível prometer uma perda de peso específica.']},
 'dureri-musculo-scheletice':{
 labels:['Evaluarea durerilor musculare și articulare','Muscle and joint pain assessment','Posouzení bolesti svalů a kloubů','Beratung bei Muskel- und Gelenkschmerzen','Valoración del dolor muscular y articular','Avaliação de dores musculares e articulares'],
 questions:['Ce va dori medicul să știe despre durere?','What will the doctor ask about the pain?','Na co se lékař zeptá ohledně bolesti?','Was möchte der Arzt über die Schmerzen wissen?','¿Qué preguntará el médico sobre el dolor?','O que vai o médico perguntar sobre a dor?'],
 answers:['Descrieți unde doare, cum a început și ce mișcări sau activități o agravează. Menționați o eventuală accidentare și orice slăbiciune sau amorțeală. Aceste informații ajută medicul să decidă cât de repede aveți nevoie de o examinare fizică.','Describe where it hurts, how it started and which movements or activities make it worse. Mention any injury, weakness or numbness. This helps the doctor assess how soon you may need a physical examination.','Popište místo bolesti, její začátek a pohyby nebo činnosti, které ji zhoršují. Uveďte případný úraz, slabost nebo necitlivost. Lékaři to pomůže posoudit, jak brzy potřebujete osobní vyšetření.','Beschreiben Sie Ort und Beginn der Schmerzen sowie Bewegungen oder Tätigkeiten, die sie verstärken. Erwähnen Sie Verletzungen, Schwäche oder Taubheitsgefühl. Das hilft einzuschätzen, wie rasch eine körperliche Untersuchung nötig ist.','Describa dónde duele, cómo empezó y qué movimientos o actividades lo empeoran. Indique si hubo una lesión, debilidad o entumecimiento. Esto ayuda a valorar la urgencia de una exploración física.','Descreva onde dói, como começou e que movimentos ou atividades agravam a dor. Refira lesões, fraqueza ou dormência. Isso ajuda a avaliar a rapidez com que pode precisar de uma observação presencial.']},
 'medic-pediatru-online':{
 labels:['Consultație generală pentru copii','General medical consultation for children','Všeobecná konzultace pro děti','Allgemeinmedizinische Beratung für Kinder','Consulta de medicina general para niños','Consulta de medicina geral para crianças'],
 questions:['Cum diferă acest serviciu de consultația cu pediatrul specialist?','How does this differ from the specialist pediatric appointment?','Jak se tato služba liší od konzultace s pediatrem?','Wie unterscheidet sich dies vom Facharzttermin beim Kinderarzt?','¿En qué se diferencia de la consulta con pediatra?','Qual é a diferença em relação à consulta com pediatra?'],
 answers:['Este o consultație de medicină generală pentru evaluarea inițială a problemelor copilului. Consultația cu pediatrul specialist este un serviciu separat. Dacă situația necesită pediatrie de specialitate sau examinare fizică, medicul vă poate îndruma.','This is a general medical consultation for an initial assessment of a child’s health concern. The specialist pediatric appointment is a separate service. The doctor can recommend specialist or in-person care where needed.','Jde o všeobecnou lékařskou konzultaci pro prvotní posouzení zdravotních potíží dítěte. Konzultace s pediatrem je samostatná služba. Lékař může podle potřeby doporučit odbornou péči nebo osobní vyšetření.','Dies ist eine allgemeinmedizinische Beratung zur ersten Einschätzung der Beschwerden eines Kindes. Die fachärztliche Kinderarztberatung ist eine separate Leistung. Bei Bedarf kann der Arzt fachärztliche oder persönliche Betreuung empfehlen.','Es una consulta de medicina general para una valoración inicial del problema del niño. La consulta con pediatra es un servicio distinto. El médico puede recomendar atención especializada o presencial si hace falta.','É uma consulta de medicina geral para uma avaliação inicial do problema da criança. A consulta com pediatra é um serviço separado. O médico pode recomendar cuidados especializados ou presenciais, se necessário.']},
 'medicina-calatoriei':{
 labels:['Consultație de medicină de călătorie','Pre-travel medical consultation','Lékařská konzultace před cestou','Reisemedizinische Beratung','Consulta médica antes de viajar','Consulta médica antes de viajar'],
 questions:['Ce informații despre călătorie sunt utile?','Which travel details should I bring?','Jaké informace o cestě jsou užitečné?','Welche Reiseangaben sind wichtig?','¿Qué datos del viaje debo preparar?','Que informações da viagem devo preparar?'],
 answers:['Pregătiți destinațiile, datele, durata și tipul călătoriei, împreună cu istoricul medical și vaccinările cunoscute. Medicul poate discuta riscurile și măsurile de prevenție; administrarea vaccinurilor nu se face prin video.','Have your destinations, dates, duration and type of trip ready, together with your medical and vaccination history. The doctor can discuss risks and prevention; vaccines cannot be administered by video.','Připravte si cíle cesty, termíny, délku a typ pobytu spolu se zdravotní a očkovací anamnézou. Lékař může probrat rizika a prevenci. Očkování nelze provést prostřednictvím videohovoru.','Halten Sie Reiseziele, Termine, Dauer und Art der Reise sowie Ihre Krankheits- und Impfgeschichte bereit. Der Arzt kann Risiken und Vorsorge besprechen. Impfungen können nicht per Video verabreicht werden.','Prepare los destinos, fechas, duración y tipo de viaje, junto con sus antecedentes médicos y vacunales. El médico puede valorar riesgos y prevención; las vacunas no se administran por videollamada.','Prepare os destinos, datas, duração e tipo de viagem, assim como o historial médico e de vacinação. O médico pode abordar riscos e prevenção; as vacinas não são administradas por videochamada.']},
 'reinnoire-tratament':{
 labels:['Evaluare pentru reînnoirea tratamentului','Treatment renewal review','Posouzení pokračování léčby','Überprüfung einer laufenden Behandlung','Revisión para renovar un tratamiento','Avaliação para renovar o tratamento'],
 questions:['Rețeta este garantată după consultație?','Is a prescription guaranteed after the appointment?','Je vystavení receptu po konzultaci zaručeno?','Ist ein Rezept nach dem Termin garantiert?','¿Se garantiza una receta tras la consulta?','A receita está garantida após a consulta?'],
 answers:['Nu. Medicul revizuiește diagnosticul, tratamentul actual, efectele și eventualele reacții adverse înainte de a decide. Pregătiți denumirea și doza medicamentului, rețetele anterioare și analizele relevante. Poate fi necesară o evaluare suplimentară.','No. The doctor reviews the diagnosis, current treatment, its effects and any side effects before deciding. Have the medicine name and dose, previous prescriptions and relevant results ready. Further assessment may be needed.','Ne. Lékař nejprve zhodnotí diagnózu, současnou léčbu, její účinky a případné nežádoucí účinky. Připravte název a dávku léku, předchozí recepty a související výsledky. Může být nutné další vyšetření.','Nein. Der Arzt prüft zunächst Diagnose, laufende Behandlung, Wirkung und mögliche Nebenwirkungen. Halten Sie Medikamentenname, Dosis, frühere Rezepte und relevante Befunde bereit. Weitere Abklärung kann nötig sein.','No. El médico revisa el diagnóstico, el tratamiento, sus efectos y posibles reacciones adversas antes de decidir. Prepare el nombre y la dosis del medicamento, recetas anteriores y resultados relevantes. Puede necesitar otra valoración.','Não. O médico revê o diagnóstico, o tratamento atual, os efeitos e possíveis reações adversas antes de decidir. Prepare o nome e a dose do medicamento, receitas anteriores e resultados relevantes. Pode ser necessária outra avaliação.']},
 'sanatate-mintala-online':{
 labels:['Evaluare generală a sănătății mintale','General mental health assessment','Všeobecné posouzení duševního zdraví','Allgemeine Beratung zur psychischen Gesundheit','Valoración general de salud mental','Avaliação geral de saúde mental'],
 questions:['Este o consultație de psihiatrie sau psihoterapie?','Is this psychiatry or psychotherapy?','Jde o psychiatrii nebo psychoterapii?','Handelt es sich um Psychiatrie oder Psychotherapie?','¿Es una consulta de psiquiatría o psicoterapia?','É uma consulta de psiquiatria ou psicoterapia?'],
 answers:['Acesta este un serviciu de medicină generală. Puteți discuta despre stres, somn, anxietate sau starea de dispoziție. Medicul face o evaluare inițială și poate recomanda psihologie ori psihiatrie când este nevoie; serviciul nu este psihoterapie.','This is a general medical service. You can discuss stress, sleep, anxiety or mood. The doctor makes an initial assessment and may recommend psychology or psychiatry when needed; this service is not psychotherapy.','Jde o službu všeobecného lékařství. Můžete probrat stres, spánek, úzkost nebo náladu. Lékař provede prvotní posouzení a podle potřeby doporučí psychologa či psychiatra. Tato služba není psychoterapie.','Dies ist eine allgemeinmedizinische Leistung. Sie können Stress, Schlaf, Ängste oder Stimmung besprechen. Der Arzt nimmt eine erste Einschätzung vor und kann psychologische oder psychiatrische Betreuung empfehlen. Die Leistung ist keine Psychotherapie.','Es un servicio de medicina general. Puede hablar de estrés, sueño, ansiedad o estado de ánimo. El médico realiza una valoración inicial y puede recomendar psicología o psiquiatría; el servicio no es psicoterapia.','É um serviço de medicina geral. Pode falar sobre stress, sono, ansiedade ou humor. O médico faz uma avaliação inicial e pode recomendar psicologia ou psiquiatria. Este serviço não é psicoterapia.']},
 'sanatatea-barbatului-online':{
 labels:['Consultație pentru sănătatea bărbatului','Men’s health consultation','Konzultace mužského zdraví','Beratung zur Männergesundheit','Consulta de salud del hombre','Consulta de saúde do homem'],
 questions:['Ce pot discuta în această consultație?','What can I discuss at this appointment?','Co mohu při této konzultaci probrat?','Welche Anliegen kann ich bei diesem Termin besprechen?','¿Qué puedo tratar en esta consulta?','O que posso abordar nesta consulta?'],
 answers:['Puteți discuta probleme urinare, sănătatea sexuală sau alte simptome care vă preocupă. Consultația este de medicină generală. Medicul vă poate recomanda investigații sau urologie dacă este necesară o evaluare de specialitate.','You can discuss urinary concerns, sexual health or other symptoms that worry you. This is a general medical consultation. The doctor may recommend tests or a urology appointment if specialist assessment is needed.','Můžete probrat močové potíže, sexuální zdraví nebo jiné příznaky, které vás znepokojují. Jde o všeobecnou lékařskou konzultaci. Lékař může doporučit vyšetření nebo urologii, pokud je potřeba odborné posouzení.','Sie können Harnwegsbeschwerden, sexuelle Gesundheit oder andere belastende Symptome besprechen. Es handelt sich um eine allgemeinmedizinische Beratung. Der Arzt kann bei Bedarf Untersuchungen oder einen urologischen Termin empfehlen.','Puede consultar problemas urinarios, salud sexual u otros síntomas que le preocupen. Es una consulta de medicina general. El médico puede recomendar pruebas o urología si necesita valoración especializada.','Pode abordar problemas urinários, saúde sexual ou outros sintomas que o preocupem. É uma consulta de medicina geral. O médico pode recomendar exames ou urologia, se precisar de avaliação especializada.']},
 'sanatatea-femeii-online':{
 labels:['Consultație pentru sănătatea femeii','Women’s health consultation','Konzultace ženského zdraví','Beratung zur Frauengesundheit','Consulta de salud de la mujer','Consulta de saúde da mulher'],
 questions:['Consultația înlocuiește un consult ginecologic?','Does this replace a gynecology appointment?','Nahrazuje tato konzultace gynekologické vyšetření?','Ersetzt die Beratung einen gynäkologischen Termin?','¿Sustituye una consulta ginecológica?','Substitui uma consulta de ginecologia?'],
 answers:['Este o evaluare de medicină generală pentru simptome și întrebări despre sănătate. Puteți discuta istoricul și rezultatele existente. Medicul vă îndrumă către ginecologie sau examinare în persoană când problema necesită acest lucru.','This is a general medical assessment of symptoms and health questions. You can discuss your history and existing results. The doctor recommends gynecology or an in-person examination when your concern requires it.','Jde o všeobecné lékařské posouzení příznaků a zdravotních otázek. Můžete probrat anamnézu a dosavadní výsledky. Pokud to potíže vyžadují, lékař doporučí gynekologii nebo osobní vyšetření.','Dies ist eine allgemeinmedizinische Einschätzung von Beschwerden und Gesundheitsfragen. Sie können Ihre Vorgeschichte und vorhandene Befunde besprechen. Bei Bedarf empfiehlt der Arzt eine gynäkologische Untersuchung oder eine Untersuchung vor Ort.','Es una valoración de medicina general de síntomas y dudas de salud. Puede comentar sus antecedentes y resultados. El médico recomienda ginecología o exploración presencial cuando el problema lo requiere.','É uma avaliação de medicina geral de sintomas e questões de saúde. Pode discutir o historial e resultados existentes. O médico recomenda ginecologia ou observação presencial quando o problema o exige.']},
 'trimiteri-si-investigatii':{
 labels:['Orientare pentru investigații și trimiteri','Tests and referral advice','Doporučení k vyšetřením a odborné péči','Beratung zu Untersuchungen und Überweisungen','Orientación sobre pruebas y derivaciones','Orientação sobre exames e referenciação'],
 questions:['Pot solicita o anumită investigație sau scrisoare medicală?','Can I request a particular test or medical letter?','Mohu požádat o konkrétní vyšetření nebo lékařskou zprávu?','Kann ich eine bestimmte Untersuchung oder einen Arztbrief anfragen?','¿Puedo solicitar una prueba o un informe concreto?','Posso pedir um exame ou relatório específico?'],
 answers:['Puteți explica de ce aveți nevoie de acel document sau de investigație și puteți aduce recomandările existente. Medicul decide ce este justificat clinic. Nu presupuneți că un document privat garantează decontare prin CNAS; verificați condițiile cu furnizorul care îl primește.','You can explain why you need the test or document and bring existing recommendations. The doctor decides what is clinically justified. Do not assume that a private document guarantees CNAS reimbursement; check the receiving provider’s requirements.','Můžete vysvětlit, proč vyšetření nebo dokument potřebujete, a předložit dosavadní doporučení. Lékař posoudí klinické odůvodnění. Soukromý dokument sám o sobě nezaručuje úhradu přes CNAS; ověřte podmínky u přijímajícího poskytovatele.','Sie können erläutern, warum Sie die Untersuchung oder das Dokument benötigen, und vorhandene Empfehlungen vorlegen. Der Arzt entscheidet nach medizinischer Begründung. Ein privates Dokument garantiert keine CNAS-Erstattung; prüfen Sie die Anforderungen des empfangenden Anbieters.','Puede explicar por qué necesita la prueba o el documento y aportar recomendaciones previas. El médico decide qué está justificado clínicamente. Un documento privado no garantiza el reembolso de CNAS; consulte los requisitos del proveedor que lo recibe.','Pode explicar por que precisa do exame ou documento e apresentar recomendações anteriores. O médico decide o que se justifica clinicamente. Um documento privado não garante comparticipação pela CNAS; confirme as condições com o prestador que o recebe.']}
};
