/**
 * Full ISO 3166-1 country list with international dial codes.
 *
 * Source of truth for every phone country picker in the app (public booking,
 * checkout, register, account, admin/doctor manual booking, admin editors).
 * Before this list the pickers offered nine hard-coded markets, so a patient
 * from anywhere else could not enter their real number.
 *
 * `code` is the lowercase ISO 3166-1 alpha-2 code — it doubles as the
 * `flag-icons` class suffix consumed by `<Flag code=… />`.
 * `dial` is the E.164 calling prefix WITHOUT the leading `+`. Territories that
 * share a prefix with their parent (Jersey/Guernsey/Isle of Man on 44,
 * Saint Barthélemy/Saint Martin on 590) keep their own row: the stored number
 * is identical, only the label differs.
 */
export type Country = {
  /** Lowercase ISO 3166-1 alpha-2 code (also the flag-icons class suffix). */
  code: string;
  /** English country name shown in the picker and matched by search. */
  name: string;
  /** E.164 calling prefix without the leading "+" (e.g. "353"). */
  dial: string;
};

/** Every country/territory, sorted by name (the picker's default order). */
export const COUNTRIES: Country[] = [
  { code: "af", name: "Afghanistan", dial: "93" },
  { code: "ax", name: "Åland Islands", dial: "358" },
  { code: "al", name: "Albania", dial: "355" },
  { code: "dz", name: "Algeria", dial: "213" },
  { code: "as", name: "American Samoa", dial: "1684" },
  { code: "ad", name: "Andorra", dial: "376" },
  { code: "ao", name: "Angola", dial: "244" },
  { code: "ai", name: "Anguilla", dial: "1264" },
  { code: "ag", name: "Antigua and Barbuda", dial: "1268" },
  { code: "ar", name: "Argentina", dial: "54" },
  { code: "am", name: "Armenia", dial: "374" },
  { code: "aw", name: "Aruba", dial: "297" },
  { code: "au", name: "Australia", dial: "61" },
  { code: "at", name: "Austria", dial: "43" },
  { code: "az", name: "Azerbaijan", dial: "994" },
  { code: "bs", name: "Bahamas", dial: "1242" },
  { code: "bh", name: "Bahrain", dial: "973" },
  { code: "bd", name: "Bangladesh", dial: "880" },
  { code: "bb", name: "Barbados", dial: "1246" },
  { code: "by", name: "Belarus", dial: "375" },
  { code: "be", name: "Belgium", dial: "32" },
  { code: "bz", name: "Belize", dial: "501" },
  { code: "bj", name: "Benin", dial: "229" },
  { code: "bm", name: "Bermuda", dial: "1441" },
  { code: "bt", name: "Bhutan", dial: "975" },
  { code: "bo", name: "Bolivia", dial: "591" },
  { code: "ba", name: "Bosnia and Herzegovina", dial: "387" },
  { code: "bw", name: "Botswana", dial: "267" },
  { code: "br", name: "Brazil", dial: "55" },
  { code: "io", name: "British Indian Ocean Territory", dial: "246" },
  { code: "vg", name: "British Virgin Islands", dial: "1284" },
  { code: "bn", name: "Brunei", dial: "673" },
  { code: "bg", name: "Bulgaria", dial: "359" },
  { code: "bf", name: "Burkina Faso", dial: "226" },
  { code: "bi", name: "Burundi", dial: "257" },
  { code: "kh", name: "Cambodia", dial: "855" },
  { code: "cm", name: "Cameroon", dial: "237" },
  { code: "ca", name: "Canada", dial: "1" },
  { code: "cv", name: "Cape Verde", dial: "238" },
  { code: "bq", name: "Caribbean Netherlands", dial: "599" },
  { code: "ky", name: "Cayman Islands", dial: "1345" },
  { code: "cf", name: "Central African Republic", dial: "236" },
  { code: "td", name: "Chad", dial: "235" },
  { code: "cl", name: "Chile", dial: "56" },
  { code: "cn", name: "China", dial: "86" },
  { code: "cx", name: "Christmas Island", dial: "61" },
  { code: "cc", name: "Cocos (Keeling) Islands", dial: "61" },
  { code: "co", name: "Colombia", dial: "57" },
  { code: "km", name: "Comoros", dial: "269" },
  { code: "ck", name: "Cook Islands", dial: "682" },
  { code: "cr", name: "Costa Rica", dial: "506" },
  { code: "ci", name: "Côte d'Ivoire", dial: "225" },
  { code: "hr", name: "Croatia", dial: "385" },
  { code: "cu", name: "Cuba", dial: "53" },
  { code: "cw", name: "Curaçao", dial: "599" },
  { code: "cy", name: "Cyprus", dial: "357" },
  { code: "cz", name: "Czechia", dial: "420" },
  { code: "cd", name: "DR Congo", dial: "243" },
  { code: "dk", name: "Denmark", dial: "45" },
  { code: "dj", name: "Djibouti", dial: "253" },
  { code: "dm", name: "Dominica", dial: "1767" },
  { code: "do", name: "Dominican Republic", dial: "1809" },
  { code: "ec", name: "Ecuador", dial: "593" },
  { code: "eg", name: "Egypt", dial: "20" },
  { code: "sv", name: "El Salvador", dial: "503" },
  { code: "gq", name: "Equatorial Guinea", dial: "240" },
  { code: "er", name: "Eritrea", dial: "291" },
  { code: "ee", name: "Estonia", dial: "372" },
  { code: "sz", name: "Eswatini", dial: "268" },
  { code: "et", name: "Ethiopia", dial: "251" },
  { code: "fk", name: "Falkland Islands", dial: "500" },
  { code: "fo", name: "Faroe Islands", dial: "298" },
  { code: "fj", name: "Fiji", dial: "679" },
  { code: "fi", name: "Finland", dial: "358" },
  { code: "fr", name: "France", dial: "33" },
  { code: "gf", name: "French Guiana", dial: "594" },
  { code: "pf", name: "French Polynesia", dial: "689" },
  { code: "ga", name: "Gabon", dial: "241" },
  { code: "gm", name: "Gambia", dial: "220" },
  { code: "ge", name: "Georgia", dial: "995" },
  { code: "de", name: "Germany", dial: "49" },
  { code: "gh", name: "Ghana", dial: "233" },
  { code: "gi", name: "Gibraltar", dial: "350" },
  { code: "gr", name: "Greece", dial: "30" },
  { code: "gl", name: "Greenland", dial: "299" },
  { code: "gd", name: "Grenada", dial: "1473" },
  { code: "gp", name: "Guadeloupe", dial: "590" },
  { code: "gu", name: "Guam", dial: "1671" },
  { code: "gt", name: "Guatemala", dial: "502" },
  { code: "gg", name: "Guernsey", dial: "44" },
  { code: "gn", name: "Guinea", dial: "224" },
  { code: "gw", name: "Guinea-Bissau", dial: "245" },
  { code: "gy", name: "Guyana", dial: "592" },
  { code: "ht", name: "Haiti", dial: "509" },
  { code: "hn", name: "Honduras", dial: "504" },
  { code: "hk", name: "Hong Kong", dial: "852" },
  { code: "hu", name: "Hungary", dial: "36" },
  { code: "is", name: "Iceland", dial: "354" },
  { code: "in", name: "India", dial: "91" },
  { code: "id", name: "Indonesia", dial: "62" },
  { code: "ir", name: "Iran", dial: "98" },
  { code: "iq", name: "Iraq", dial: "964" },
  { code: "ie", name: "Ireland", dial: "353" },
  { code: "im", name: "Isle of Man", dial: "44" },
  { code: "il", name: "Israel", dial: "972" },
  { code: "it", name: "Italy", dial: "39" },
  { code: "jm", name: "Jamaica", dial: "1876" },
  { code: "jp", name: "Japan", dial: "81" },
  { code: "je", name: "Jersey", dial: "44" },
  { code: "jo", name: "Jordan", dial: "962" },
  { code: "kz", name: "Kazakhstan", dial: "7" },
  { code: "ke", name: "Kenya", dial: "254" },
  { code: "ki", name: "Kiribati", dial: "686" },
  { code: "xk", name: "Kosovo", dial: "383" },
  { code: "kw", name: "Kuwait", dial: "965" },
  { code: "kg", name: "Kyrgyzstan", dial: "996" },
  { code: "la", name: "Laos", dial: "856" },
  { code: "lv", name: "Latvia", dial: "371" },
  { code: "lb", name: "Lebanon", dial: "961" },
  { code: "ls", name: "Lesotho", dial: "266" },
  { code: "lr", name: "Liberia", dial: "231" },
  { code: "ly", name: "Libya", dial: "218" },
  { code: "li", name: "Liechtenstein", dial: "423" },
  { code: "lt", name: "Lithuania", dial: "370" },
  { code: "lu", name: "Luxembourg", dial: "352" },
  { code: "mo", name: "Macau", dial: "853" },
  { code: "mg", name: "Madagascar", dial: "261" },
  { code: "mw", name: "Malawi", dial: "265" },
  { code: "my", name: "Malaysia", dial: "60" },
  { code: "mv", name: "Maldives", dial: "960" },
  { code: "ml", name: "Mali", dial: "223" },
  { code: "mt", name: "Malta", dial: "356" },
  { code: "mh", name: "Marshall Islands", dial: "692" },
  { code: "mq", name: "Martinique", dial: "596" },
  { code: "mr", name: "Mauritania", dial: "222" },
  { code: "mu", name: "Mauritius", dial: "230" },
  { code: "yt", name: "Mayotte", dial: "262" },
  { code: "mx", name: "Mexico", dial: "52" },
  { code: "fm", name: "Micronesia", dial: "691" },
  { code: "md", name: "Moldova", dial: "373" },
  { code: "mc", name: "Monaco", dial: "377" },
  { code: "mn", name: "Mongolia", dial: "976" },
  { code: "me", name: "Montenegro", dial: "382" },
  { code: "ms", name: "Montserrat", dial: "1664" },
  { code: "ma", name: "Morocco", dial: "212" },
  { code: "mz", name: "Mozambique", dial: "258" },
  { code: "mm", name: "Myanmar", dial: "95" },
  { code: "na", name: "Namibia", dial: "264" },
  { code: "nr", name: "Nauru", dial: "674" },
  { code: "np", name: "Nepal", dial: "977" },
  { code: "nl", name: "Netherlands", dial: "31" },
  { code: "nc", name: "New Caledonia", dial: "687" },
  { code: "nz", name: "New Zealand", dial: "64" },
  { code: "ni", name: "Nicaragua", dial: "505" },
  { code: "ne", name: "Niger", dial: "227" },
  { code: "ng", name: "Nigeria", dial: "234" },
  { code: "nu", name: "Niue", dial: "683" },
  { code: "nf", name: "Norfolk Island", dial: "672" },
  { code: "kp", name: "North Korea", dial: "850" },
  { code: "mk", name: "North Macedonia", dial: "389" },
  { code: "mp", name: "Northern Mariana Islands", dial: "1670" },
  { code: "no", name: "Norway", dial: "47" },
  { code: "om", name: "Oman", dial: "968" },
  { code: "pk", name: "Pakistan", dial: "92" },
  { code: "pw", name: "Palau", dial: "680" },
  { code: "ps", name: "Palestine", dial: "970" },
  { code: "pa", name: "Panama", dial: "507" },
  { code: "pg", name: "Papua New Guinea", dial: "675" },
  { code: "py", name: "Paraguay", dial: "595" },
  { code: "pe", name: "Peru", dial: "51" },
  { code: "ph", name: "Philippines", dial: "63" },
  { code: "pl", name: "Poland", dial: "48" },
  { code: "pt", name: "Portugal", dial: "351" },
  { code: "pr", name: "Puerto Rico", dial: "1787" },
  { code: "qa", name: "Qatar", dial: "974" },
  { code: "cg", name: "Republic of the Congo", dial: "242" },
  { code: "re", name: "Réunion", dial: "262" },
  { code: "ro", name: "Romania", dial: "40" },
  { code: "ru", name: "Russia", dial: "7" },
  { code: "rw", name: "Rwanda", dial: "250" },
  { code: "bl", name: "Saint Barthélemy", dial: "590" },
  { code: "sh", name: "Saint Helena", dial: "290" },
  { code: "kn", name: "Saint Kitts and Nevis", dial: "1869" },
  { code: "lc", name: "Saint Lucia", dial: "1758" },
  { code: "mf", name: "Saint Martin", dial: "590" },
  { code: "pm", name: "Saint Pierre and Miquelon", dial: "508" },
  { code: "vc", name: "Saint Vincent and the Grenadines", dial: "1784" },
  { code: "ws", name: "Samoa", dial: "685" },
  { code: "sm", name: "San Marino", dial: "378" },
  { code: "st", name: "São Tomé and Príncipe", dial: "239" },
  { code: "sa", name: "Saudi Arabia", dial: "966" },
  { code: "sn", name: "Senegal", dial: "221" },
  { code: "rs", name: "Serbia", dial: "381" },
  { code: "sc", name: "Seychelles", dial: "248" },
  { code: "sl", name: "Sierra Leone", dial: "232" },
  { code: "sg", name: "Singapore", dial: "65" },
  { code: "sx", name: "Sint Maarten", dial: "1721" },
  { code: "sk", name: "Slovakia", dial: "421" },
  { code: "si", name: "Slovenia", dial: "386" },
  { code: "sb", name: "Solomon Islands", dial: "677" },
  { code: "so", name: "Somalia", dial: "252" },
  { code: "za", name: "South Africa", dial: "27" },
  { code: "kr", name: "South Korea", dial: "82" },
  { code: "ss", name: "South Sudan", dial: "211" },
  { code: "es", name: "Spain", dial: "34" },
  { code: "lk", name: "Sri Lanka", dial: "94" },
  { code: "sd", name: "Sudan", dial: "249" },
  { code: "sr", name: "Suriname", dial: "597" },
  { code: "se", name: "Sweden", dial: "46" },
  { code: "ch", name: "Switzerland", dial: "41" },
  { code: "sy", name: "Syria", dial: "963" },
  { code: "tw", name: "Taiwan", dial: "886" },
  { code: "tj", name: "Tajikistan", dial: "992" },
  { code: "tz", name: "Tanzania", dial: "255" },
  { code: "th", name: "Thailand", dial: "66" },
  { code: "tl", name: "Timor-Leste", dial: "670" },
  { code: "tg", name: "Togo", dial: "228" },
  { code: "tk", name: "Tokelau", dial: "690" },
  { code: "to", name: "Tonga", dial: "676" },
  { code: "tt", name: "Trinidad and Tobago", dial: "1868" },
  { code: "tn", name: "Tunisia", dial: "216" },
  { code: "tr", name: "Turkey", dial: "90" },
  { code: "tm", name: "Turkmenistan", dial: "993" },
  { code: "tc", name: "Turks and Caicos Islands", dial: "1649" },
  { code: "tv", name: "Tuvalu", dial: "688" },
  { code: "ug", name: "Uganda", dial: "256" },
  { code: "ua", name: "Ukraine", dial: "380" },
  { code: "ae", name: "United Arab Emirates", dial: "971" },
  { code: "gb", name: "United Kingdom", dial: "44" },
  { code: "us", name: "United States", dial: "1" },
  { code: "uy", name: "Uruguay", dial: "598" },
  { code: "uz", name: "Uzbekistan", dial: "998" },
  { code: "vu", name: "Vanuatu", dial: "678" },
  { code: "va", name: "Vatican City", dial: "39" },
  { code: "ve", name: "Venezuela", dial: "58" },
  { code: "vn", name: "Vietnam", dial: "84" },
  { code: "vi", name: "U.S. Virgin Islands", dial: "1340" },
  { code: "wf", name: "Wallis and Futuna", dial: "681" },
  { code: "eh", name: "Western Sahara", dial: "212" },
  { code: "ye", name: "Yemen", dial: "967" },
  { code: "zm", name: "Zambia", dial: "260" },
  { code: "zw", name: "Zimbabwe", dial: "263" },
];

/**
 * Markets the app actually sells in — pinned to the top of the picker, in
 * business priority order, so the common case stays a one-click choice.
 * Keys are ISO codes; the app's legacy aliases ("sp" → es, "rm" → ro) are
 * resolved in `dial-codes.ts`.
 */
export const PRIORITY_COUNTRY_CODES = [
  "ie",
  "cz",
  "pt",
  "es",
  "ro",
  "mt",
  "br",
  "gb",
  "pk",
] as const;

/** Extra search terms per country — common alternate/short names people type. */
export const COUNTRY_SEARCH_ALIASES: Record<string, string[]> = {
  ae: ["uae", "emirates", "dubai", "abu dhabi"],
  cd: ["congo kinshasa", "zaire", "democratic republic of the congo"],
  cg: ["congo brazzaville"],
  ci: ["ivory coast"],
  cz: ["czech republic", "czech"],
  gb: ["uk", "britain", "great britain", "england", "scotland", "wales", "northern ireland"],
  hk: ["china"],
  kp: ["dprk"],
  kr: ["korea"],
  la: ["lao"],
  mm: ["burma"],
  mo: ["china"],
  nl: ["holland"],
  ps: ["gaza", "west bank"],
  ru: ["russian federation"],
  sz: ["swaziland"],
  tl: ["east timor"],
  tr: ["turkiye", "türkiye"],
  us: ["usa", "united states of america", "america"],
  va: ["holy see"],
  vi: ["usvi", "virgin islands"],
  vn: ["viet nam"],
  za: ["rsa"],
};
