-- AlterTable
ALTER TABLE "Asset" ADD COLUMN "focalX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Asset" ADD COLUMN "focalY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Asset" ADD COLUMN "zoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
