import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {services as copy,shared,locales} from './content-briefs/service-copy.mjs';
const require=createRequire(import.meta.url), htmlRequire=createRequire(require.resolve('../../backend/node_modules/sanitize-html'));
const {parseDocument,DomUtils}=htmlRequire('htmlparser2');
const root='seo/romania', origin='https://www.myglobalhealth.online';
const read=async p=>JSON.parse((await fs.readFile(`${root}/${p}`,'utf8')).replace(/^\uFEFF/,''));
const write=async(p,v)=>fs.writeFile(`${root}/${p}`,typeof v==='string'?v:JSON.stringify(v,null,2));
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const plain=s=>DomUtils.textContent(parseDocument(s??'')).replace(/\s+/g,' ').trim();
const csv=async(p,rows)=>{assert(rows.length,`Empty ${p}`);const keys=[...new Set(rows.flatMap(Object.keys))];const cell=v=>`"${String(v??'').replaceAll('"','""')}"`;await write(p,[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\n')+'\n')};
const pages=await read('raw/public-inventory-2026-09-13.json');const extras=await read('raw/linked-extra-pages-2026-09-13.json');const allPages=[...pages,...extras];
const apiFiles=await fs.readdir(`${root}/raw/api`);const apis={};
for(const file of apiFiles.filter(n=>/-[A-Z]{2}\.json$/.test(n))){const r=await read(`raw/api/${file}`);const obj=r.data.service??r.data.doctor;if(obj)apis[file]=r;}
const doctors=(await read('raw/api/doctors-RO.json')).data;
const serviceRoster=(await read('raw/api/services-RO.json')).data;
const current=await read('raw/pages_current-2026-09-13.json'),previous=await read('raw/pages_previous-2026-09-13.json'),queries=await read('raw/gsc-query-current-2026-09-13.json');
assert(!current.hasMore&&!previous.hasMore&&!queries.hasMore);
const countryNames=['România','Romania','Rumunsko','Rumänien','Rumanía','Roménia'];
const pageByUrl=new Map(allPages.map(p=>[p.url,p]));
function source(p){const a=new URL(p.url).pathname.split('/');return apis[`${a[3]}-${a[4]}-${a[2]?.toUpperCase()}.json`];}
const group=p=>{const a=new URL(p.url).pathname.split('/');return a[3]==='doctors'&&a[4]?'doctor':a[3]==='services'?'service':a[3]==='blog'&&a[4]?'article':a[3]==='tools'?'tool':a[3]??'home'};
const faqHeadings=['Frequently Asked Questions','Často kladené otázky','Häufig gestellte Fragen','Preguntas frecuentes','Perguntas frequentes','Întrebări frecvente'];
export function embedded(body=''){
 const matches=[...body.matchAll(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi)];const last=matches.at(-1);
 if(!last||!faqHeadings.includes(plain(last[1])))return {body,faqs:[],section:''};
 const section=body.slice(last.index);const faqs=[...section.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)].map(m=>{const t=plain(m[1]);const pos=t.indexOf('?');assert(pos>0&&pos<t.length-1,'Malformed embedded FAQ');return {question:t.slice(0,pos+1),answer:t.slice(pos+1).trim()}});
 assert(faqs.length>0,'Empty embedded section');return {body:body.slice(0,last.index).trim(),faqs,section};
}
const serviceDrafts=[],doctorDrafts=[],coverage=[],facts=[],supply=[];
for(const p of pages.filter(p=>['service','doctor'].includes(group(p)))){
 const response=source(p);assert(response?.ok);const s=response.data.service??response.data.doctor,locale=p.locale,idx=locales.indexOf(locale);const em=embedded(s.detailBody);
 coverage.push({url:p.url,locale,source_model:group(p)==='service'?'ServiceFaq + ServiceTranslation.detailBody':'DoctorFaq',resolved_locale:s.resolvedLocale,native_api_count:s.faqs.length,native_html_count:p.faqs.length,schema_count:p.schemaFaqCount,embedded_count:em.faqs.length,total_visible_questions:p.faqs.length+em.faqs.length,gap:p.faqs.length+em.faqs.length===0?'missing':'present',source_checked_at:response.checkedAt});
 assert.equal(s.faqs.length,p.faqs.length,'FAQ source/render mismatch');
 if(group(p)==='service'){
   const assigned=doctors.filter(d=>s.assignedDoctorIds.includes(d.id));
   supply.push({url:p.url,locale,service:s.slug,kind:s.kind,bookability:s.bookability.state,reason:s.bookability.reasonCode,assigned_doctors:assigned.map(d=>d.fullName).join(' | '),consultation_languages:[...new Set(assigned.flatMap(d=>d.languages))].join(' | '),next_available_at:s.bookability.nextAvailableAt,price_cents:s.basePriceCents,currency:s.currencyCode,duration_minutes:s.durationMinutes,source_checked_at:response.checkedAt});
   if(s.bookability.state!=='BOOKABLE')continue;
   const c=copy[s.slug];assert(c,`Missing copy ${s.slug}`);const faqs=[{question:c.questions[idx],answer:c.answers[idx]},...shared[locale].map(([question,answer])=>({question,answer}))];
   const metaTail=['Consultații în română și engleză. Verificați medicul și orele disponibile înainte de rezervare.','Consultations in Romanian and English. Check the doctor and available times before booking.','Konzultace v rumunštině a angličtině. Před rezervací si ověřte lékaře a dostupné termíny.','Beratung auf Rumänisch und Englisch. Prüfen Sie Arzt und verfügbare Termine vor der Buchung.','Consultas en rumano e inglés. Consulte el médico y los horarios disponibles antes de reservar.','Consultas em romeno e inglês. Consulte o médico e os horários disponíveis antes de marcar.'][idx];
   const after={seoTitle:`${c.labels[idx]} | ${countryNames[idx]}`,seoDescription:`${c.labels[idx]}. ${metaTail}`,heroTitle:c.labels[idx],detailBody:em.body,faqs};
   const before={seoTitle:s.seoTitle,seoDescription:s.seoDescription,heroTitle:s.heroTitle,detailBody:s.detailBody,faqs:s.faqs};
   serviceDrafts.push({url:p.url,slug:s.slug,locale,sourceModel:'Service + ServiceTranslation + ServiceFaq',sourceFingerprint:hash(s),before,after,removedEmbeddedFaqs:em.faqs,removedEmbeddedSection:em.section,source:`raw/api/services-${s.slug}-${locale.toUpperCase()}.json`,status:'local draft; not applied',review:'editorial and service-scope checked; no named clinical approval',migration:'Group all six locales by service. Remove exact old embedded section and write matching translated native FAQs atomically. Preserve unrelated fields and hidden/unexported rows via authenticated preflight.'});
 }else{
   const booked=s.faqs.find(f=>f.sortOrder===4);assert(booked,'Missing booking FAQ');
   const prefix=[`Alegeți un interval disponibil pentru ${s.fullName}.`,`Choose an available appointment with ${s.fullName}.`,`Vyberte si volný termín u ${s.fullName}.`,`Wählen Sie einen verfügbaren Termin bei ${s.fullName}.`,`Elija una cita disponible con ${s.fullName}.`,`Escolha um horário disponível com ${s.fullName}.`][idx];
   const languageAnswers=[`Consultațiile sunt în română sau engleză. Verificați limba și ora la rezervare. Disponibilitatea se poate schimba; nu putem promite o programare în aceeași zi.`,`Consultations are in Romanian or English. Check the language and time when booking. Availability can change; a same-day appointment cannot be promised.`,`Konzultace probíhají v rumunštině nebo angličtině. Jazyk a čas si ověřte při rezervaci. Dostupnost se může změnit; termín na tentýž den nelze slíbit.`,`Die Beratung erfolgt auf Rumänisch oder Englisch. Prüfen Sie Sprache und Uhrzeit bei der Buchung. Die Verfügbarkeit kann sich ändern; ein Termin am selben Tag lässt sich nicht zusagen.`,`Las consultas son en rumano o inglés. Compruebe el idioma y la hora al reservar. La disponibilidad puede cambiar; no se garantiza una cita para el mismo día.`,`As consultas são em romeno ou inglês. Confirme a língua e a hora ao marcar. A disponibilidade pode mudar; não se pode garantir uma consulta no próprio dia.`][idx];
   const patchFaqs=[{id:booked.id,before:{question:booked.question,answer:booked.answer},after:{question:booked.question,answer:`${prefix} ${languageAnswers}`}}];
   if(s.slug==='dr-alexandra-palaga'){
     const scope=s.faqs.find(f=>f.sortOrder===1);const c=copy['consultatie-pediatrie'];patchFaqs.push({id:scope.id,before:{question:scope.question,answer:scope.answer},after:{question:c.questions[idx],answer:`${c.answers[idx]} ${shared[locale][2][1]}`}});
   }
   doctorDrafts.push({url:p.url,slug:s.slug,locale,sourceFingerprint:hash(s),source:`raw/api/doctors-${s.slug}-${locale.toUpperCase()}.json`,before:{seoTitle:s.seoTitle},after:{seoTitle:s.seoTitle?.replaceAll('Paga','Palaga')??s.seoTitle},faqPatches:patchFaqs,status:'local draft; not applied',scope:'DoctorFaq rows are shared across countries. Recheck all country associations and preserve untouched FAQs before applying; use a country overlay if wording becomes Romania-specific.',held:'Do not standardize Brindus specialty or expand credentials; registry homepage is not independent verification of detailed biography claims.'});
 }
}
assert.equal(coverage.length,120);assert.equal(serviceDrafts.length,96);assert.equal(doctorDrafts.length,18);
for(const d of doctors){facts.push({doctor:d.fullName,slug:d.slug,active:d.active,consultation_languages:d.languages.join(' | '),bookability:d.bookability.state,next_available_at:d.bookability.nextAvailableAt,assigned_services:serviceRoster.filter(s=>d.assignedServices.some(a=>a.serviceId===s.id)).map(s=>s.slug).join(' | '),stored_registration_verified:d.registrationVerified,registry_url:d.medicalRegistrationUrl,independent_registry_verification:'not established; supplied URL is registry homepage',last_reviewed_at:d.lastReviewedAt??'',biography_disposition:d.slug.includes('brindus')?'hold specialty harmonization; conflicting locale titles':'retain credential claims pending primary evidence',source:'raw/api/doctors-RO.json'});}
await write('content-briefs/service-drafts.json',serviceDrafts);await write('content-briefs/doctor-drafts.json',doctorDrafts);await csv('faq-coverage.csv',coverage);await csv('doctor-service-language-matrix.csv',supply);await csv('doctor-profile-fact-register.csv',facts);

// Keyword ownership uses visible GSC evidence and explicit service-fit rules, not volume alone.
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'');
const rules=[[/scrisoar|trimitere|investigatii/,'trimiteri-si-investigatii'],[/a doua opin|second opinion/,'a-doua-opinie-medicala'],[/pediatr/,'consultatie-pediatrie'],[/neurolog/,'consultatie-neurologie'],[/caderea par|cadere par|alopec/,'caderea-parului-online'],[/greutat|slabire/,'controlul-greutatii'],[/reinno|reteta|prescript/,'reinnoire-tratament'],[/boli cronice/,'boli-cronice-online'],[/medic online|doctor online|consultati.*online|consultatie.*online|medicina de familie/,'medic-online-romania']];
const selected=new Map(),excluded=[];
function add(keyword,owner,locale,sourceName,metrics={},note=''){
 const key=`${locale}|${normalize(keyword)}`;const existing=selected.get(key);
 const row={keyword,locale,market:'Romania',location_code:2642,owner_url:owner,source:sourceName,search_volume:metrics.searchVolume??metrics.search_volume??'',keyword_difficulty:metrics.keywordDifficulty??metrics.keyword_difficulty??'',intent:metrics.intent??metrics.main_intent??'',cpc:metrics.cpc??'',priority:owner.includes('/services/')?'P1':owner.includes('/doctors/')?'P1':'P2',notes:note};
 if(!existing)selected.set(key,row);else{if(row.search_volume!==''){existing.search_volume=row.search_volume;existing.keyword_difficulty=row.keyword_difficulty;existing.cpc=row.cpc;existing.intent=row.intent}if(!existing.source.includes(sourceName))existing.source+=` | ${sourceName}`;}
}
const gscByQuery=new Map();for(const r of queries.rows){const [q,u]=r.keys;if(!pageByUrl.has(u)||/^[%+]|nhs|\bnear me\b|urgent care|www\./i.test(q))continue;const old=gscByQuery.get(q);if(!old||r.impressions>old.impressions)gscByQuery.set(q,r);}
for(const r of gscByQuery.values()){const [q,u]=r.keys,p=pageByUrl.get(u);if(['book','legal','careers','press','contact'].includes(group(p)))continue;
 const clean=normalize(q);const relevant=/calor|kalor|kcal|\bbmi\b|\bimc\b|body mass|masa corpor|korp|tensi|blood pressure|blutdruck|\btlak\b|hipotens|hipertens|ovula|fertil|frucht|sarcin|naster|pregnan|due date|geburt|tehot|gravidez|embaraz|adhd|asrs|osteoporo|sore throat|amigdal|mandli|halsschmerz|dor de garganta|dolor de garganta|diabet|scrisoar|boli cronice|global\s*health|palaga|brindus|bica|medic|doctor|arzt|lekar/.test(clean);
 if(!relevant){excluded.push({keyword:q,seed:'GSC',reason:'No clear page-topic relevance; retain raw evidence only',search_volume:''});continue;}
 if(p.url.includes('/services/')&&!rules.some(([re])=>re.test(clean))){excluded.push({keyword:q,seed:'GSC',reason:'Commercial query does not match verified service intent',search_volume:''});continue;}
 let owner=u,locale=p.locale;if(/pediatru/.test(clean)){owner=`${origin}/romania/ro/services/consultatie-pediatrie`;locale='ro';}
 add(q,owner,locale,'GSC visible query',{},owner!==u?'Romanian query reassigned to Romanian specialist owner; original landing URL retained in raw GSC':'Observed owner; query language may differ from page locale. Confirm intent before rewriting.');}
const reviewedProviderTerms=new Set([
 'scrisoare medicala','cat are valabilitate o scrisoare medicala','ce este scrisoarea medicala','eliberare scrisoare medicala','scrisoare medicala de la medicul specialist','cine elibereaza scrisoarea medicala',
 'consultatii medicale online','doctor online','medic online','medic pediatru online','platforma consultatii online','intreaba un medic online','discuta cu un medic online','ce face un medic pediatru','doctor online romania','ce este un medic pediatru','pediatru online','consultatii online neurologie','neurolog online','a doua opinie medicala','a doua opinie medicala online','consultatie online',
 'alopecie areata','caderea parului','caderea parului cauze','caderea parului tratament','alopecie femei','caderea parului la femei','analize pentru caderea parului','tratament alopecie femei','ce boli ascunde caderea parului','alopecie tratament','alopecie areata femei','tratament pentru caderea parului la femei','caderea parului la barbati','tratament caderea parului femei','caderea parului la barbati 20 de ani','tratament pentru caderea parului la barbati','caderea parului cauze femei','caderea parului la femei cauze si tratament','caderea parului cauze barbati','caderea parului la barbati tratament','tipuri de alopecie femei','medicina de familie','controlul greutatii','controlul greutatii corporale'
].map(normalize));
for(const file of ['research_ro','research_focused']){
 const r=await read(`raw/${file}-2026-09-13.json`);
 for(const batch of r.results.filter(r=>r.ok))for(const k of batch.rows){
  const q=normalize(k.keyword);let reason='';
  if(/medic chat|regina maria|medlife|sanador|docbook|ringdoc|medicover|synevo|\b365\b/.test(q))reason='Competitor brand';
  else if(/gratis|gratuit|non stop|nonstop|24\/7|urgent/.test(q))reason='Free/always-on/emergency intent unsupported';
  else if(/bucuresti|cluj|iasi|timisoara|galati|constanta|brasov|sibiu|cabinet|program|salariu|rezident|posturi|facultat|pdf|model|formular|\bcnas\b|\bcas\b|curricula|lista|inscrier|contract/.test(q))reason='Physical location, employment, form or public-system intent; no commercial owner';
  else if(/certsign|atestat|pasaport|buletin|acte|fares|ceai|supliment|masca|sampon|ulei|leac|naturist|silueta perfecta|retete|reinoire/.test(q))reason='Nonmedical renewal, shopping or home-remedy intent';
  else if(/reinno|reteta|prescript/.test(q)&&!/medic|tratament|online|prescrip/.test(q))reason='Renewal/prescription wording lacks medical service context';
  const rule=rules.find(([re])=>re.test(q));if(!reason&&!rule)reason='No evidenced existing service intent';
  if(!reason&&!reviewedProviderTerms.has(q))reason='Reviewed exclusion: specialist, shopping, form, foreign-market or otherwise unsupported intent';
  if(reason){excluded.push({keyword:k.keyword,seed:batch.seed,reason,search_volume:k.searchVolume??''});continue;}
  let owner=`${origin}/romania/ro/services/${rule[1]}`;
  if(/scrisoar/.test(q))owner=`${origin}/romania/ro/blog/scrisoare-medicala-cine-o-elibereaza`;
  add(k.keyword,owner,'ro',file,k,'Rule-mapped candidate; service scope checked, specific query meaning still governs use.');
 }
}
for(const d of serviceDrafts)add(copy[d.slug].labels[locales.indexOf(d.locale)],d.url,d.locale,'Editorial service label',{},'Proposed page intent; no search-volume claim');
for(const d of doctorDrafts){const doc=doctors.find(x=>x.slug===d.slug);add(doc.fullName,d.url,d.locale,'Verified public roster',{},'Clinician-name intent; no measured query demand claimed');}
const keywords=[...selected.values()];await csv('03-keyword-master.csv',keywords);await csv('keyword-exclusions.csv',excluded);
const byOwner=new Map();for(const k of keywords){if(!byOwner.has(k.owner_url))byOwner.set(k.owner_url,[]);byOwner.get(k.owner_url).push(k)}
const draftMap=new Map([...serviceDrafts,...doctorDrafts].map(d=>[d.url,d]));
const matrix=[],map=[],gaps=[],reviews=[];
for(const p of allPages){const type=group(p),d=draftMap.get(p.url),s=source(p),obj=s?.data.service??s?.data.doctor;const rowKeywords=byOwner.get(p.url)??[];const cover=coverage.find(c=>c.url===p.url);const unsupported=type==='service'&&obj?.bookability?.state!=='BOOKABLE';let action=d?'draft ready':unsupported?'hold: no approved doctor':p.status!==200?'broken linked URL':p.robots?.includes('noindex')?'retain noindex':'retain pending targeted editorial review';let reason='No verified change needed from this bounded evidence; retain existing text. Clinical/legal claims are not independently re-certified.';
 if(d)reason=type==='service'?'Add native FAQs; replace any exact embedded FAQ block. Scope/language-aware metadata and H1 drafted.':'Correct booking language/availability; narrow pediatric emergency scope; fix Palaga name typo where present. Other credential claims retained pending evidence.';
 if(unsupported)reason='No assigned approved doctor. Do not market or draft as bookable; operational decision needed.';
 if(type==='book')reason='Booking route has a client-rendered shell; assess indexability and user flow separately. Not a keyword landing page.';
 if(type==='legal')reason='Preserve legal body and intentional noindex variants; translated headings and legal accuracy require separate field-level decisions.';
 if(p.status===404)reason='Remove or correct inbound link; do not redirect to an unrelated service or recreate an unstaffed sick-note offer.';
 const primary=type==='service'&&copy[obj?.slug]?copy[obj.slug].labels[locales.indexOf(p.locale)]:type==='doctor'?obj.fullName:(rowKeywords.sort((a,b)=>Number(b.search_volume||0)-Number(a.search_volume||0))[0]?.keyword??p.h1[0]??p.title);
 matrix.push({URL:p.url,'page type':type,locale:p.locale,'primary keyword':type==='book'||p.status!==200?'not applicable':primary,'keyword evidence':rowKeywords.length?'see keyword master':'editorial topic only; no demand claim','secondary keywords':rowKeywords.filter(k=>k.keyword!==primary).slice(0,6).map(k=>k.keyword).join(' | '),'original title':p.title,'optimized title':d?.after.seoTitle??p.title,'original meta description':p.description,'optimized meta description':d?.after.seoDescription??p.description,'live H1':p.h1.join(' | '),'proposed H1':d?.after.heroTitle??p.h1.join(' | '),'description optimized':type==='service'&&d?'draft':'no','bio optimized':'no','FAQs optimized':d?'exact local draft':cover?.gap==='missing'?'held':'retained','deslop completed':d?'changed draft fields reviewed':'not rewritten','factual verification completed':d?'service/language source checked; credentials not independently verified':'inventory checks only','clinical review required':['service','doctor','article','tool'].includes(type)?'claim-dependent; no named approval recorded':'legal owner for legal-body changes','implementation status':action,'reason for anything left unchanged':reason,'HTTP status':p.status,canonical:p.canonical,'hreflang entries':p.hreflang?.length,'indexable':p.robots?.includes('noindex')?'no':'yes','structured data types':p.schemaTypes?.join(' | '),'native FAQ count':cover?.native_api_count??p.faqs?.length,'embedded FAQ count':cover?.embedded_count??'not evaluated outside service body','consultation languages':obj?.languages?.join(' | ')??supply.find(x=>x.url===p.url)?.consultation_languages??'not applicable','bookability':obj?.bookability?.state??'not applicable','live reviewed at':p.checkedAt,'source fingerprint':d?.sourceFingerprint??p.sha256});
 map.push({url:p.url,page_role:type,locale:p.locale,primary_keyword:type==='book'||p.status!==200?'not applicable':primary,keyword_source:rowKeywords.length?'master':'editorial label',priority:unsupported?'HOLD':d?'P1':'P2',status:action,cannibalisation_control:type==='doctor'?'Clinician name only':type==='service'?'One clinical service intent; preserve GP/specialist distinction':'Retain current information intent; no commercial keyword stuffing'});
 gaps.push({url:p.url,locale:p.locale,page_type:type,faq_gap:cover?.gap??'not a service/profile gap',embedded_questions:cover?.embedded_count??'',action,reason,priority:unsupported?'HOLD':d?'P1':'P2',draft:d?`content-briefs/${type==='service'?'service':'doctor'}-drafts.json`:''});
 if(d||unsupported)reviews.push({url:p.url,locale:p.locale,source_status:'current public source captured',review_status:d?'editorial/source review complete; publication pending':'operations hold',reviewer_name:'',reviewed_at:'',approved_sha256:'',draft_sha256:d?hash(d.after):'',claims_requiring_review:type==='doctor'?'credentials, regulated specialty, cross-market FAQ ownership':'clinical scope, document eligibility, removal of old embedded claims',source:d?.source??'',notes:reason});
}
await csv('target-page-inventory.csv',allPages.map(p=>({url:p.url,locale:p.locale,status:p.status,final_url:p.finalUrl,title:p.title,description:p.description,h1:p.h1.join(' | '),word_count:p.body?.split(' ').length,canonical:p.canonical,robots:p.robots,hreflang_count:p.hreflang.length,faq_native_count:p.faqs.length,source:p.url,checked_at:p.checkedAt,sha256:p.sha256})));
await csv('page-by-page-completion-matrix.csv',matrix);await csv('05-url-keyword-map.csv',map);await csv('04-content-gap.csv',gaps);await csv('clinical-review-register.csv',reviews);
const competitors=await read('raw/competitor-pages-2026-09-13.json');await csv('competitor-page-inventory.csv',competitors.map(p=>({url:p.url,status:p.status??'unavailable',title:p.title??'',h2:p.h2?.join(' | ')??'',words:p.body?.split(' ').length??'',review:p.error??(p.status===200?'retrieved; claims attributed to competitor':'blocked/error; no content conclusions'),checked_at:p.checkedAt??''})));
const backlinks=await read('raw/backlinks_medic_chat-2026-09-13.json');await csv('08-backlink-opportunities.csv',backlinks.backlinks.rows.map(r=>({prospect_url:r.urlFrom,domain:r.domainFrom,source:'OpenSEO competitor backlinks: medic.chat',domain_rank:r.domainFromRank,spam_score:r.spamScore,priority:['start-up.ro','www.doctorulzilei.ro'].includes(r.domainFrom)?'review individually':'exclude/deprioritize',reason:r.domainFrom==='start-up.ro'?'Romanian telemedicine coverage; pitch verified service/language facts':r.domainFrom==='www.doctorulzilei.ro'?'Health publisher; only a clinician-reviewed educational contribution':'No verified relevant editorial placement opportunity',contact_path:'not established; inspect editorial/contact page before outreach',outreach_status:'not contacted'})));
function totals(data){const result={};for(const r of data.rows){const url=r.keys[0];const type=url.includes('/services/')?'services':url.includes('/doctors/')?'doctor profiles':url.includes('/tools/')?'tools':url.includes('/blog/')?'articles':'other';result[type]??={clicks:0,impressions:0};result[type].clicks+=r.clicks;result[type].impressions+=r.impressions;}return result}
const stats={sitemapPages:pages.length,linkedExtras:extras.length,reachablePages:allPages.filter(p=>p.status===200).length,locales:pages.reduce((a,p)=>(a[p.locale]=(a[p.locale]??0)+1,a),{}),serviceVariants:coverage.filter(c=>c.source_model.startsWith('Service')).length,embeddedServiceVariants:coverage.filter(c=>c.embedded_count>0).length,embeddedQuestions:coverage.reduce((n,c)=>n+c.embedded_count,0),trueFaqGaps:coverage.filter(c=>c.gap==='missing').length,serviceDrafts:serviceDrafts.length,doctorDrafts:doctorDrafts.length,newNativeQuestions:serviceDrafts.reduce((n,d)=>n+d.after.faqs.length,0),doctorFaqPatches:doctorDrafts.reduce((n,d)=>n+d.faqPatches.length,0),keywordRows:keywords.length,excludedRows:excluded.length,current:totals(current),previous:totals(previous)};
await write('raw/package-summary.json',stats);
await write('content-briefs/README.md',`# Exact Romania draft package\n\n${serviceDrafts.length} service/locale drafts and ${doctorDrafts.length} doctor/locale drafts. All are local candidates, not published. Service drafts contain ${stats.newNativeQuestions} proposed native FAQs and exact old embedded blocks. Doctor drafts contain ${stats.doctorFaqPatches} exact FAQ patches.\n\nRead the page completion matrix and clinical register before applying. Source fingerprints describe public projections; an authenticated export must capture hidden rows and verify storage before a write. No database credential was available in this clone; no direct database read or write occurred.\n\nApply service locales as one set so removing an English embedded block cannot leave another locale without answers. Do not append a second FAQ section. All six translated candidates say consultations are Romanian/English.\n\nThe specialist pain service is excluded from publishable drafts because it has no approved doctor. Existing doctor credential FAQs and biographies are retained, not certified. Brindus specialty harmonization remains held.\n\nChanged text was checked against public scope and deslop rules; no human-authorship or named medical-review claim is made. Sources: raw/api, faq-coverage.csv and doctor-service-language-matrix.csv.\n`);
// Every retained keyword points at an observed page and every clinical variant has a disposition.
assert(keywords.every(k=>pageByUrl.has(k.owner_url)));assert.equal(new Set(matrix.map(r=>r.URL)).size,allPages.length);
assert.equal(coverage.filter(c=>c.embedded_count>0).length,22);assert.equal(coverage.reduce((n,c)=>n+c.embedded_count,0),187);
assert.equal(coverage.filter(c=>c.gap==='missing').length,80);
for(const d of serviceDrafts){assert.equal(d.after.faqs.length,4);assert(!/[—]/.test(JSON.stringify(d.after.faqs)));assert(d.after.faqs.at(-1).answer.includes('112'));}
console.log(JSON.stringify(stats,null,2));
